/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * Desarrollado por: Garyn Carrillo Caballero, Auditor de Sistemas.
 * Created on 2/05/2015, 07:52:03 AM
 */
package FondosLey;

import BD_As400.JConection;
import java.io.File;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;



/**
 *
 * @author Garyn Carrillo
 */
public class JDistribucion extends javax.swing.JFrame {
    SimpleDateFormat d = new SimpleDateFormat("yyyyMMdd");
    /**
     * Creates new form JDistribucion
     */
     private double DebAgr, CreAgr;
     private String FechaIncial , FechaFinal;
     private String FechaMes;
     private JConection JBase_Datos;
     private Connection Cn;
     private String Usuario;
     
     private Vector Cabecera;
     private Vector Fila;
     private Vector Detalle;
     
     private Vector CabBanco;
     private Vector FilaBanco;
     private Vector DetBanco;
     
     private Vector CabBancoInsert;
     private Vector FilaBancoInsert;
     private Vector DetBancoInsert;
     
     private Vector CabConciliacion;
     private Vector FilaConciliacion;
     private Vector DetConciliacion;
     
     
     private String FechaUsuario;
     private String PPeriodo;
     private String NumeroFormato = "##############";
     private DecimalFormat JFormato ;
     private double TotalIngresos;
     
     private boolean CTabla1, CTabla2;
     
     private Vector Cab_CDTs;
     private Vector Det_CDTs;
     private Vector Fila_CDTs;
     
     private double DebFin=0;
     private double CredFin=0;
     
     private double DebCon=0;
     private double CredCon=0;
     
     private double NetoSistema=0;
     private double NetoCalculado=0;
    public JDistribucion(JConection JBase_Datos3, Connection Cn2, String Usuariox, String PPeriodo) {
        
        this.Cab_CDTs = new Vector();
        Det_CDTs = new Vector();
        CTabla1 =  CTabla2=false;
        java.util.Date ahora = new java.util.Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyyMMdd");
        FechaUsuario =formateador.format(ahora);
        
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        this.Usuario = Usuariox;
        this.PPeriodo =PPeriodo;
        Cabecera = new Vector();
        Fila = new Vector();
        
        this.CabBanco = new Vector();
        this.FilaBanco = new Vector();
        
        this.CabBancoInsert = new Vector();
        this.FilaBancoInsert = new Vector();
        
        
        this.CabConciliacion = new Vector();
        this.FilaConciliacion = new Vector(); 
        
        this.getCabecera();
        JFormato= new DecimalFormat(NumeroFormato);
        this.CabeceraBancoInsert();
        initComponents();
         AutoCompleteDecorator.decorate(jCCuentas);
        this.getCuentas_Financieras();
        this.getTablaConciliacion(this.PPeriodo);
        this.getInformacion_Distribucion();
        this.setCabecera_Conciliacion();
        this.getInformacion_Conciliacion();
        jLabel1.setText("Periodo: "+this.PPeriodo);
        jLabel2.setText("Periodo: "+this.PPeriodo);
        this.getCombo_CDTs();
        this.getCombo_Fondos_CDTs();
        
        jXDatePicker1.setFormats("yyyyMMdd");
        jXDatePicker2.setFormats("yyyyMMdd");
        jXDatePicker3.setFormats("yyyyMMdd");
        jXDatePicker4.setFormats("yyyyMMdd");
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCCuentas = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jXDatePicker3 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton16 = new javax.swing.JButton();
        jCDT_Nro = new javax.swing.JTextField();
        jCDT_Cuenta = new javax.swing.JComboBox();
        jCDT_Fec_Cierre = new javax.swing.JTextField();
        jCDT_Valor = new javax.swing.JTextField();
        jCDT_Fec_Aper = new javax.swing.JTextField();
        jCDT_Estado = new javax.swing.JComboBox();
        jCDT_Periodo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribucion de Fondos de Ley");

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta Sistema", "Decripcion Cta", "Debito-Contable", "Credito-Contable", "Neto-Contable", "Porcentaje", "Valor-Calculado", "Diferencias"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Periodo: ");

        jButton9.setText("Imprimir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jButton1)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Distribuciones", jPanel1);

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Fecha", "Numero Documento", "Credito", "Debito", "Periodo"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jCCuentas.setEditable(true);

        jButton3.setText("Mover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Fecha", "Numero Documento", "Credito", "Debito", "Periodo"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Periodo:");

        jButton10.setText("Imprimir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Ver");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Ver");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton2)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2)))
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jXDatePicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton10)
                    .addComponent(jButton12))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Banco", jPanel2);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta Contable", "Cuenta Financiera", "Descripcion", "Neto Financiero", "Neto Contable", "Neto Calculado", "Diferencias"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton7.setText("Conciliar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Imprimir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Conciliacion", jPanel3);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "Cuenta", "Fondo", "Fecha Mov", "Fecha Apertura", "Fecha de Cierre", "Valor", "Periodo", "Estado"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable5MousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        jButton13.setText("Guardar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Elimniar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Todos", "Activa", "Inactivas" }));

        jButton16.setText("Buscar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jCDT_Cuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        jCDT_Estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Activo", "Inactivo" }));

        jLabel3.setText("Nro");

        jLabel4.setText("Cuenta");

        jLabel5.setText("Fecha Apertura");

        jLabel6.setText("Fecha Cierre");

        jLabel7.setText("Valor");

        jLabel8.setText("Estado");

        jLabel9.setText("Periodo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4)
                                .addGap(127, 127, 127)
                                .addComponent(jLabel9)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel8))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel3)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton16))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCDT_Nro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCDT_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCDT_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCDT_Fec_Aper, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCDT_Fec_Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCDT_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addComponent(jCDT_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton13)
                                    .addComponent(jButton14))
                                .addGap(0, 384, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCDT_Nro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCDT_Fec_Aper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCDT_Fec_Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCDT_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCDT_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCDT_Cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCDT_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jButton13)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Titulos y Otros", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.FechaIncial = d.format(jXDatePicker1.getDate()).toString().trim();
        this.FechaFinal = d.format(jXDatePicker2.getDate()).toString().trim();
        this.Fila.clear();
        this.getCuentAportes();
        this.getDistribucionGeneral();
        this.getSaldoApotes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       String BFechaInicial = d.format(jXDatePicker3.getDate()).toString().trim();
       String BFechaFinal = d.format(jXDatePicker4.getDate()).toString().trim();
       this.setCabeceraBanco();
       getInformacionBanco(BFechaInicial.trim(),BFechaFinal.trim(), jCCuentas.getSelectedItem().toString() );
       //Buscar_Movimiento_Fosyga(this.BFechaInicial.getText().trim() , BFechaFinal.getText().trim(), "28521501", "900462447" );
    }//GEN-LAST:event_jButton2ActionPerformed
    public void CabeceraBancoInsert(){
        this.CabBancoInsert.add("Cuenta");
        this.CabBancoInsert.add("Fecha");
        this.CabBancoInsert.add("Numero Documento");
        this.CabBancoInsert.add("Credito");
        this.CabBancoInsert.add("Debito");
        this.CabBancoInsert.add("Periodo");
        
    }
    public void setMover(){
        
        this.DetBancoInsert = new Vector();
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
        this.FilaBancoInsert.add(DetBancoInsert);
        this.jTable3.setModel(new javax.swing.table.DefaultTableModel(this.FilaBancoInsert, this.CabBancoInsert));
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       try{
           if ( !jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString().trim().equals("")){
                 this.setMover();
           }else{
                    JOptionPane.showMessageDialog(this,"Debe Seleccionar el periodo al cual desea conciliar ");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"ClickButton() "+e.getMessage() );
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (! this.Guardar()){
            JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente " );
        }else{
            JOptionPane.showMessageDialog(this,"Se Guardo Correctamente " );
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setBorrarFila_tabla3();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(this.Guardar_Distribucion()){
               JOptionPane.showMessageDialog(this,"Se Guardo Correctamente  "); 
        }else{
            JOptionPane.showMessageDialog(this,"No se Pudo Guardar Correctamente  "); 
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        this.FechaIncial = d.format(jXDatePicker1.getDate()).toString().trim();
        this.FechaFinal = d.format(jXDatePicker2.getDate()).toString().trim();
        
        if ((!FechaIncial.equals(""))|| (!FechaFinal.equals(""))) {
            if( this.getConciliar()){
                this.getInformacion_Conciliacion();
                JOptionPane.showMessageDialog(this,"Se Guardo Correctamente  "); 
            }else{
                JOptionPane.showMessageDialog(this,"No se Pudo Guardar Correctamente  "); 
            }
        }else{
            JOptionPane.showMessageDialog(this," Debe diligenciar la feha  "); 
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
              
      this.FechaIncial = d.format(jXDatePicker1.getDate()).toString().trim();
      this.FechaFinal = d.format(jXDatePicker2.getDate()).toString().trim();
        
      if( !(this.FechaIncial.trim().equals(""))  &&!(this.FechaFinal.trim().equals(""))){
            JJasper  GenPdf = new JJasper();
            GenPdf.setTipo(1);
            GenPdf.setFechaInicial(this.FechaIncial.trim());
            GenPdf.setFechaFinal(this.FechaFinal.trim());
            GenPdf.setPPeriodo(PPeriodo);
            GenPdf.setConeccion(Cn);
            GenPdf.start();
      }else{
          JOptionPane.showMessageDialog(this,"Debe diligenciar la fecha inicial y fecha Final en la Primera pestaña  "); 
      }
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.FechaIncial = d.format(jXDatePicker1.getDate()).toString().trim();
        this.FechaFinal = d.format(jXDatePicker2.getDate()).toString().trim();
         if( !(FechaIncial.trim().equals(""))  &&!(FechaFinal.trim().equals(""))){
            JJasper  GenPdf = new JJasper();
            GenPdf.setTipo(2);
            GenPdf.setFechaInicial(FechaIncial.trim());
            GenPdf.setFechaFinal(FechaFinal.trim());
            GenPdf.setPPeriodo(PPeriodo);
            GenPdf.setConeccion(Cn);
            GenPdf.start();
            
      }else{
          JOptionPane.showMessageDialog(this,"Debe diligenciar la fecha inicial y fecha Final en la Primera pestaña  "); 
      }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
            JJasper  GenPdf = new JJasper();
            GenPdf.setTipo(3);
            GenPdf.setPPeriodo(PPeriodo);
            GenPdf.setConeccion(Cn);
            GenPdf.start();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
             String PFecha = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
             String PNumDoc = jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString();
             String PCuenta = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
             JDetalleContable Frm_JDetalleContable =  new JDetalleContable(this.JBase_Datos, this.Cn, PFecha, PNumDoc, PCuenta);
             Frm_JDetalleContable.setVisible(true);       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," Frm_Detalle()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            String PFecha = jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
            String PNumDoc = jTable3.getValueAt(jTable3.getSelectedRow(), 2).toString();
            String PCuenta = jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
            JDetalleContable Frm_JDetalleContable =  new JDetalleContable(this.JBase_Datos, this.Cn, PFecha, PNumDoc, PCuenta);
            Frm_JDetalleContable.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," Frm_Detalle()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        this.get_CDTS_();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.Save_CDTs();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        // TODO add your handling code here:
        try{
            jCDT_Nro.setText(jTable5.getValueAt(jTable5.getSelectedRow(),0).toString());
            //jTable5.getValueAt(jTable5.getSelectedRow(),1).toString();
            //jTable5.getValueAt(jTable5.getSelectedRow(),2).toString();
            //jTable5.getValueAt(jTable5.getSelectedRow(),3).toString();
            jCDT_Fec_Aper.setText(jTable5.getValueAt(jTable5.getSelectedRow(),4).toString());
            jCDT_Fec_Cierre.setText(jTable5.getValueAt(jTable5.getSelectedRow(),5).toString());
            jCDT_Valor.setText(jTable5.getValueAt(jTable5.getSelectedRow(),6).toString());
            //jTable5.getValueAt(jTable5.getSelectedRow(),7).toString();
            //jTable5.getValueAt(jTable5.getSelectedRow(),8).toString();
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this," Click_Tabla()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable5MousePressed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         try{
            String NroCdt =jTable5.getValueAt(jTable5.getSelectedRow(),0).toString();
            String NroCuenta =jTable5.getValueAt(jTable5.getSelectedRow(),1).toString();
            String Str_Sql ="select * from selinlib.JFCDT where NROCDT ="+NroCdt+" and ctacon="+NroCuenta.trim();
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(rs.next()){
              Str_Sql = "Delete from selinlib.JFCDT where NROCDT ="+NroCdt;
              boolean Guardar = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
              if(Guardar){
                DefaultTableModel Modelo =(DefaultTableModel) jTable5.getModel();
                Modelo.removeRow(jTable5.getSelectedRow());
                jTable5.updateUI();
                JOptionPane.showMessageDialog(this," Se Elimino Correcetamente  "); 
              }
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this," Click_Tabla()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jButton14ActionPerformed
    
    public void Save_CDTs(){
        try {
            String Str_Sql ="select * from selinlib.JFCDT where NROCDT ="+jCDT_Nro.getText();
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(rs.next()){
                Str_Sql ="update selinlib.JFCDT"
                        +" set ctacon= '"+jCDT_Cuenta.getSelectedItem().toString().trim()+"'"
                        +" , fecmov=20160518"
                        +" , fecape="+jCDT_Fec_Aper.getText().trim()
                        +" , feccie="+jCDT_Fec_Cierre.getText().trim()
                        +" , valor="+jCDT_Valor.getText().trim()
                        +" , periodo="+jCDT_Periodo.getSelectedItem().toString().trim()
                        +" , estado='"+jCDT_Estado.getSelectedItem().toString().trim()+"'"
                        + "where nrocdt='"+jCDT_Nro.getText().trim()+"'";
            }else{
                Str_Sql ="insert  into selinlib.JFCDT (nrocdt, ctacon, fecmov, fecape, feccie, valor, periodo, estado) values('"+
                        jCDT_Nro.getText().trim()+"','"+jCDT_Cuenta.getSelectedItem().toString().trim()+"',"
                        +"20160518,"+jCDT_Fec_Aper.getText().trim()+","+jCDT_Fec_Cierre.getText().trim()+","
                        +jCDT_Valor.getText().trim()+","+jCDT_Periodo.getSelectedItem().toString().trim()+",'"+jCDT_Estado.getSelectedItem().toString().trim()
                        +"')";
            }
            boolean Guardar = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
            if(Guardar){
                JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");     
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," Save_CDTs()  "+e.getMessage()); 
        }
        
    }
    public void Cab_CDTs_(){
        Cab_CDTs.clear();
        Cab_CDTs.add("Nro");
        Cab_CDTs.add("Cuenta");
        Cab_CDTs.add("Fondo");
        Cab_CDTs.add("Feha Mov");
        Cab_CDTs.add("Fecha Apertura");
        Cab_CDTs.add("Fecha Cierre");
        Cab_CDTs.add("Valor");
        Cab_CDTs.add("Periodo");
        Cab_CDTs.add("Estado");
        
    }
    public void get_CDTS_(){
        try {
            String Str_Sql ="";
            this.Cab_CDTs_();
            if (jComboBox1.getSelectedItem().toString().trim().equals("Todos")){
                Str_Sql ="select * from selinlib.JFCDT";
            }else{
                if (jComboBox1.getSelectedItem().toString().trim().equals("Activo")){
                    Str_Sql ="select * from selinlib.JFCDT where Estado='Activo'";
                }else{
                    if (jComboBox1.getSelectedItem().toString().trim().equals("Inactivo")){
                        Str_Sql ="select * from selinlib.JFCDT where Estado='Inactivo'";
                    }
                }
            }
            if(!Str_Sql.trim().equals("")){
               ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
               Det_CDTs.clear();
               while(rs.next()){
                   Fila_CDTs = new Vector();
                   Fila_CDTs.add(rs.getString("NROCDT"));
                   Fila_CDTs.add(rs.getString("CTACON"));
                   Fila_CDTs.add("");
                   Fila_CDTs.add(rs.getInt("FECMOV"));
                   Fila_CDTs.add(rs.getInt("FECAPE"));
                   Fila_CDTs.add(rs.getInt("FECCIE"));
                   Fila_CDTs.add(rs.getDouble("VALOR"));
                   Fila_CDTs.add(rs.getInt("PERIODO"));
                   Fila_CDTs.add(rs.getString("ESTADO"));
                   Det_CDTs.add(Fila_CDTs);
               }
               jTable5.setModel(new javax.swing.table.DefaultTableModel(Det_CDTs, Cab_CDTs)); 
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," get_CDTS_()  "+e.getMessage()); 
        }
    }
    
    
    
    public void setCabecera_Conciliacion(){
        this.CabConciliacion.add("Cuenta Contable");
        this.CabConciliacion.add("Cuenta Financiera");
        this.CabConciliacion.add("Descripcion");
        this.CabConciliacion.add("Neto Financiero");
        this.CabConciliacion.add("Neto Contable");
        this.CabConciliacion.add("Neto Calculado");
        this.CabConciliacion.add("Diferencias");
    }
    
    public void getInformacion_Conciliacion(){
        try {
            String Str_Sql = "select * from SELINLIB.JFDISTRDIF WHERE period="+this.PPeriodo;
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            this.FilaConciliacion.clear();
            while(Rs.next()){
                this.DetConciliacion = new Vector();
                this.DetConciliacion.add(Rs.getString("CTACON"));
                this.DetConciliacion.add(Rs.getString("CTAFIN"));
                this.DetConciliacion.add(Rs.getString("DESCRI"));
                this.DetConciliacion.add(this.JFormato.format(Rs.getDouble("NTOBAN")));
                this.DetConciliacion.add(this.JFormato.format(Rs.getDouble("NTOCON")));
                this.DetConciliacion.add(this.JFormato.format(Rs.getDouble("NTOCAL")));
                this.DetConciliacion.add("+");
                this.FilaConciliacion.add(this.DetConciliacion);
            }
            Rs.close();
            this.jTable4.setModel(new javax.swing.table.DefaultTableModel(this.FilaConciliacion, this.CabConciliacion));
            this.setAnchoColumnas_Tabla4();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getInformacion_Conciliacion() "+e.getMessage()); 
        }
    }
     public boolean getConciliar(){
        boolean Rs=false;
            try {
                String Str_Sql ="DELETE FROM selinlib.JFDISTRDIF WHERE PERIOD="+this.PPeriodo;
                Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);                                           
                
                
                Str_Sql = "INSERT INTO selinlib.JFDISTRDIF "                                  
                                 +" SELECT T1.CTACON , CTAFIN , DESCRIP ,BANCO, NTOSIS, NTOCAL ,"+this.PPeriodo +",'"+this.Usuario+"','"+this.FechaUsuario+"'"     
                                 +" FROM ( "      
                                 +" SELECT CUENTA , CTAFIN , CTACON  ,  "       
                                 +" SUM(DEBITO) BANCO FROM SELINLIB.JFDISTRIBU AS T2  "                                                  
                                 +" LEFT JOIN SELINLIB.JFDISTRBAN AS B "       
                                 +" ON (CTAFIN=  CHAR(CUENTA)   ) "    
                                 +" WHERE MARCA='CN' AND B.PERIODO ="+this.PPeriodo+" AND CTACON <> 520520 and CTACON <> 522010  "
                                 +" GROUP BY CUENTA  , CTAFIN , CTACON  ) AS T1 "
                                 +" LEFT JOIN SELINLIB.JFDISTRCAB AS T2 "
                                 +" ON (T1.CTACON =T2.CTACON) "
                                 +" WHERE PERIODO = "+this.PPeriodo ;
                 
                 Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
                 //System.out.println(" ***  "+Str_Sql);
                 //Agupacion fosfec
                 Str_Sql = "INSERT INTO selinlib.JFDISTRDIF "
                        +" select CUENAGR ,CUENFIN, DESCRIP, ntoban , ntocon, ntocal, "     
                        +" periodo  "+",'"+this.Usuario+"','"+this.FechaUsuario+"'"      
                         + " from  "                                       
                        +" (select cuenagr , CUENFIN, "                                     
                        +" t1.descrip , sum(ntosis) ntocon , sum(ntocal) ntocal  ,periodo "
                        +" from selinlib.JFDISTRAGR as t1 , selinlib.JFDISTRCAB as t2 "    
                        +" where t1.cuecon=t2.ctacon "                                     
                        +" and periodo = "+this.PPeriodo                                      
                        +" group by cuenagr , t1.descrip , periodo  ,CUENFIN "             
                        +"  ) as t1 , (select  cuenta, sum(debito) ntoban   "                
                        +"  from selinlib.JFDISTRBAN as tt "          
                        +"  where cuenta in( 18109503 , 112005117, 112005121) and periodo="+this.PPeriodo                                       
                        +" group by cuenta ) as t2 "                                      
                        +" where t1.cuenfin=t2.cuenta  ";
                 
                 Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
                 
                 //Cambio de Norma 2018/04/25
                 // FOSFEC
                 Str_Sql="select * from selinlib.JFDISTRAGR where Marca = 'X' ";
                 ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 //System.out.println(" ****  "+Str_Sql);
                 while(rs.next()){
                      String Cuenta_Financiera = rs.getString("CUENFIN");
                      String Cuenta_Agrupa = rs.getString("CUENAGR");
                      String Cuenta_con = rs.getString("CUECON");
                      
                          this.getTotal_Financiero(Cuenta_Financiera);
                          NetoSistema=0;
                          NetoCalculado=0;
                          get_Calculo_Porcentaje(Cuenta_con , this.PPeriodo);
                          
                          Str_Sql ="select * from selinlib.JFDISTRDIF where PERIOD='"+this.PPeriodo+"' and ctacon='"+Cuenta_Agrupa.trim()+"'";
                          ResultSet resultado = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                           if(resultado.next()){
                               Str_Sql= "update selinlib.JFDISTRDIF set "
                                    + " ntoban=ntoban+"+this.DebFin+""
                                    + " , ntocon= ntocon+"+NetoSistema
                                    + " , ntocal= ntocal+"+NetoCalculado   
                                    + " where Period='"+this.PPeriodo+"'"
                                    + " and ctacon='"+Cuenta_Agrupa.trim()+"' ";
                                //System.out.println("------ "+Str_Sql);
                                Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
                           }else{
                               
                                //
                                //
                                //String SQL =" insert into selinlib.JFDISTRDIF (CTACON,CTAFIN, DESCRI,NTOBAN, NTOCON, NTOCAL, PERIOD,USUARI,FECHA)"
                                //    + " VALUES ('"+Cuenta_Agrupa.trim()+"','"+Cuenta_Financiera.trim()+"' ,'ADMINISTRACION',"+(PDeb-PCre)+","+NetoSistema+","+NetoCalculado
                                //    +",'"+this.PPeriodo+"','"+this.Usuario+"','"+this.FechaUsuario+"')";
                                //Rs = JBase_Datos.Exc_Sql(this.Cn,SQL); 
                           }
                 }
                 rs.close();
                 
                 
                 
                 //GASTOS ADMINISTRATIVOS
                 Str_Sql="select * from selinlib.JFDISTRAGR where Marca = 'A'";
                 ResultSet res = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 
                 double PDeb=0, PCre=0;
                 String Cuenta_Agrupa="";
                 String Cuenta_Financiera="";
                 while(res.next()){
                     Cuenta_Financiera = res.getString("CUENFIN");
                     Cuenta_Agrupa = res.getString("CUENAGR");
                     this.getTotal_Financiero(Cuenta_Financiera);
                     PDeb =PDeb+this.DebFin;
                     PCre = PCre+this.CredFin;
                 }
                 if(!Cuenta_Agrupa.equals("")){
                     NetoSistema=0;
                     NetoCalculado=0;
                     get_Calculo_Porcentaje(Cuenta_Agrupa ,this.PPeriodo);
                     //Buscar en la Tabla JFDISTRCAB
                     String SQL =" insert into selinlib.JFDISTRDIF (CTACON,CTAFIN, DESCRI,NTOBAN, NTOCON, NTOCAL, PERIOD,USUARI,FECHA)"
                            + " VALUES ('"+Cuenta_Agrupa.trim()+"','"+Cuenta_Financiera.trim()+"' ,'ADMINISTRACION',"+(PDeb-PCre)+","+NetoSistema+","+NetoCalculado
                            +",'"+this.PPeriodo+"','"+this.Usuario+"','"+this.FechaUsuario+"')";
                     Rs = JBase_Datos.Exc_Sql(this.Cn,SQL); 
                     
                 }
                 
                 res.close();
                 
                 
                 //CUOTA MONETARIA
                 Str_Sql="select * from selinlib.JFDISTRAGR where Marca = 'B'";
                 ResultSet res2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 
                 PDeb=0; PCre=0;
                 Cuenta_Agrupa="";
                 Cuenta_Financiera="";
                 while(res2.next()){
                     Cuenta_Financiera = res2.getString("CUENFIN");
                     Cuenta_Agrupa = res2.getString("CUENAGR");
                     //System.out.println(""+Cuenta_Financiera);
                     this.getTotal_Financiero(Cuenta_Financiera);
                     PDeb =PDeb+this.DebFin;
                     PCre = PCre+this.CredFin;
                 }
                 if(!Cuenta_Agrupa.equals("")){
                     NetoSistema=0;
                     NetoCalculado=0;
                     get_Calculo_Porcentaje(Cuenta_Agrupa ,this.PPeriodo);
                     //Buscar en la Tabla JFDISTRCAB
                     String SQL =" insert into selinlib.JFDISTRDIF (CTACON,CTAFIN, DESCRI,NTOBAN, NTOCON, NTOCAL, PERIOD,USUARI,FECHA)"
                            + " VALUES ('"+Cuenta_Agrupa.trim()+"','"+Cuenta_Financiera.trim()+"' ,'CUOTA MONETARIA',"+(PDeb-PCre)+","+NetoSistema+","+NetoCalculado
                            +",'"+this.PPeriodo+"','"+this.Usuario+"','"+this.FechaUsuario+"')";
                     Rs = JBase_Datos.Exc_Sql(this.Cn,SQL); 
                     
                 }
                 
                 res2.close();
                 
                 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"getConciliar()  "+e.getMessage()); 
            }
            return Rs;
    }
    public void get_Calculo_Porcentaje(String CtaCon , String Periodo){
        try {
            String Str_Sql = "select * from  selinlib.JFDISTRCAB where Periodo="+Periodo+" and ctacon='"+CtaCon+"' ";
            ResultSet rs_cal = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            
            if(rs_cal.next()){
                NetoCalculado = rs_cal.getDouble("NTOCAL");
                NetoSistema   = rs_cal.getDouble("NTOSIS");
            }
            rs_cal.close();
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this,"get_Calculo_Porcentaje(String CtaCon , String Periodo)  "+e.getMessage()); 
        }
    }
  
    
    public void getTotal_Financiero(String Cuenta_Financiera){
        try {
                    String Str_Sql = "select cuenta , sum(debito) as debito, sum(Credit) as credito from "
                              + " selinlib.JFDISTRBAN"
                              + " where periodo="+this.PPeriodo
                              + " and cuenta="+Cuenta_Financiera
                              + " group  by cuenta";
                      //System.out.println("+++++++++++++++++++++ "+Str_Sql);
                      ResultSet rs_fin = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                      this.DebFin =0;
                      this.CredFin =0;
                      
                      if(rs_fin.next()){
                          DebFin =rs_fin.getDouble("debito");
                          CredFin =rs_fin.getDouble("credito");
                      }
                      rs_fin.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getTotal_Financiero(String Cuenta_Financiera)  "+e.getMessage()); 
        }
    }
    public void setAnchoColumnas_Tabla1(){
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(230);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(10);
    }
    
    public void setAnchoColumnas_Tabla4(){
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(230);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTable4.getColumnModel().getColumn(5).setPreferredWidth(10);
        jTable4.getColumnModel().getColumn(6).setPreferredWidth(10);
    }
    
    public boolean getExiste_Distribucion(String Cuenta , String Periodo){
        boolean Control = false;
        try {
            String Str_Sql =" select * from selinlib.JFDISTRCAB where Ctacon="+Cuenta+" and Periodo="+Periodo;
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(Rs.next()){
                Control=true;
            }
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getExiste_Distribucion()  "+e.getMessage()); 
        }
        
        return Control;
    }
    public void getInformacion_Distribucion(){
        try {
            String Str_Sql = "select * from selinlib.JFDISTRCAB where periodo="+this.PPeriodo;
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);

            while(Rs.next()){
                this.Detalle = new Vector();
                this.Detalle.add(Rs.getString("ctacon"));
                this.Detalle.add(Rs.getString("descrip"));
                this.Detalle.add(this.JFormato.format( Rs.getDouble("debsis") ) );
                this.Detalle.add(this.JFormato.format( Rs.getDouble("cresis")));
                this.Detalle.add(this.JFormato.format( Rs.getDouble("ntosis")));
                this.Detalle.add(Rs.getDouble("porcen"));
                this.Detalle.add(this.JFormato.format( Rs.getDouble("ntocal")));
                this.Detalle.add(this.JFormato.format( Rs.getDouble("difere")));
                this.Fila.add(this.Detalle);
            }
            
            this.jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cabecera));
            Rs.close();
            this.setAnchoColumnas_Tabla1();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getInformacion_Distribucion()  "+e.getMessage()); 
        }
    }
    
    
    public boolean Guardar_Distribucion(){
        boolean Rs=false;
        try {
            int Cantidad = jTable1.getRowCount();
            for (int i = 0; i < Cantidad; i++) {
                String Cuenta = this.jTable1.getValueAt(i, 0).toString();
                String Descrip = this.jTable1.getValueAt(i, 1).toString();
                double DebSis = Double.valueOf(this.jTable1.getValueAt(i, 2).toString());        
                double CreSis = Double.valueOf(this.jTable1.getValueAt(i, 3).toString());        
                double NetoSis = Double.valueOf(this.jTable1.getValueAt(i, 4).toString());
                double Porcentaje = Double.valueOf(this.jTable1.getValueAt(i, 5).toString());
                double VlrCalculado = Double.valueOf(this.jTable1.getValueAt(i, 6).toString());
                double Diferencias = Double.valueOf(this.jTable1.getValueAt(i, 7).toString());
                if (!this.getExiste_Distribucion(Cuenta, this.PPeriodo)){
                    String Str_Sql ="Insert into selinlib.JFDISTRCAB "
                                    + " VALUES ('"+Cuenta+"' , '"+Descrip+"' ,"+CreSis+" , "+DebSis+" , "
                                    +NetoSis+" ,"+Porcentaje+", "+VlrCalculado+", "+Diferencias+","+this.PPeriodo+",'"+this.Usuario+"','"+this.FechaUsuario+"')";
                    Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                }else{
                    String Str_Sql= "update selinlib.JFDISTRCAB "
                                    + "set cresis="+CreSis
                                    + ", debsis="+DebSis
                                    + ", ntosis="+NetoSis
                                    + ", porcen="+Porcentaje
                                    + ", ntocal="+VlrCalculado
                                    + ", difere="+Diferencias
                                    + ", usuari='"+this.Usuario+"'"
                                    + ", fecha='"+this.FechaUsuario+"'"
                                    +" where Ctacon="+Cuenta+" and Periodo="+this.PPeriodo;
                    Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Guardar_Distribucion()  "+e.getMessage()); 
        }
        return Rs;
    }
    
     
    public boolean EliminaDetalle(){
        boolean Rs=false;
        try {
                String Cuenta = jTable3.getValueAt(this.jTable3.getSelectedRow(), 0).toString();
                String Fecha = jTable3.getValueAt(this.jTable3.getSelectedRow(), 1).toString();
                String NumDocumento = jTable3.getValueAt(this.jTable3.getSelectedRow(), 2).toString();
                String Periodo = jTable3.getValueAt(this.jTable3.getSelectedRow(), 5).toString();
                String Str_Sql = "delete from selinlib.JFDISTRBAN where fecha="+Fecha+" and numdoc="+NumDocumento+
                    " and periodo="+Periodo+" and cuenta="+Cuenta;    
                Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"EliminaDetalle()  "+e.getMessage()); 
        }
        return Rs;
    }
    
    public void setBorrarFila_tabla3(){
       try{ 
            if (EliminaDetalle()){
                DefaultTableModel Modelo =(DefaultTableModel) jTable3.getModel();
                Modelo.removeRow(jTable3.getSelectedRow());
                jTable3.updateUI();
            }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"El registro seleccionado debe Contener informacion"); 
       }
    }
    
    
    public boolean getExiste(String NumDocumento, String Periodo, String Cuenta, String Fecha){
        boolean Control = false;
        try {
            String Str_Sql = "select * from selinlib.JFDISTRBAN where fecha="+Fecha+" and numdoc="+NumDocumento+
                    " and periodo="+Periodo+" and cuenta="+Cuenta;    
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(Rs.next()){
                Control=true;
            }
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getExiste() "+e.getMessage() );
        }
        return Control;
    }
    public void getTablaConciliacion(String Periodo){
        try {
            String Str_Sql = "select * from selinlib.JFDISTRBAN where Periodo="+Periodo;
            System.out.println(""+Str_Sql);
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            System.out.println("****** ++++  "+Str_Sql);
            while(Rs.next()){
                DetBancoInsert = new Vector();
                DetBancoInsert.add(Rs.getInt("Cuenta"));
                DetBancoInsert.add(Rs.getInt("Fecha"));
                DetBancoInsert.add(Rs.getInt("Numdoc"));
                DetBancoInsert.add(Rs.getInt("Credit"));
                DetBancoInsert.add(Rs.getInt("Debito"));
                DetBancoInsert.add(Rs.getInt("Periodo"));
                //System.out.println(""+Rs.getInt("Numdoc"));
                FilaBancoInsert.add(DetBancoInsert);
            }
            this.jTable3.setModel(new javax.swing.table.DefaultTableModel(this.FilaBancoInsert, this.CabBancoInsert));
            Rs.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getTablaConciliacion()-1 ** "+e.getMessage() );
        }
    }

    public boolean Guardar(){
        boolean Rs=false;
        try {
            int Cantidad =  jTable3.getRowCount();
            for (int i = 0; i < Cantidad; i++) {
                String Cuenta = jTable3.getValueAt(i, 0).toString();
                String Fecha = jTable3.getValueAt(i, 1).toString();
                String NumDocumento = jTable3.getValueAt(i, 2).toString();
                double Credito = Double.valueOf( jTable3.getValueAt(i, 3).toString());
                double Debito = Double.valueOf( jTable3.getValueAt(i, 4).toString());
                String Periodo = jTable3.getValueAt(i, 5).toString();

                if (!this.getExiste(NumDocumento, Periodo, Cuenta, Fecha)){
                    String Str_Sql ="insert into selinlib.JFDISTRBAN"
                                    + " VALUES("+Cuenta+" , "+Periodo+" , "+Fecha+" , "+NumDocumento+" , "+Debito+" , "
                                    + ""+Credito+", '"+this.Usuario+"',"+FechaUsuario+")";
                     Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                     if(Rs==false){
                           JOptionPane.showMessageDialog(this,"No se pudo insertar " ); 
                     }
                }else{
                    String Str_Sql ="update selinlib.JFDISTRBAN"
                                    + " set Debito="+Debito
                                    + ", Credit="+Credito
                                    + ", Usuari='"+Usuario+"' "
                                    + ", Fecusu="+FechaUsuario
                                    + " where fecha="+Fecha+" and Periodo="+Periodo+" and Cuenta="+Cuenta+" and numdoc="+NumDocumento;
                     Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                     if(Rs==false){
                           JOptionPane.showMessageDialog(this,"No se pudo Actualizar " ); 
                     }
                }
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Guardar() "+e.getMessage() );
        }
        return Rs;
    }
    public void getCabecera(){
        this.Cabecera.add("Cuenta Sistema");
        this.Cabecera.add("Cta Aportes");
        this.Cabecera.add("Debito-Contable");
        this.Cabecera.add("Credito-Contable");
        this.Cabecera.add("Neto-Contable");
        this.Cabecera.add("Porcentaje");
        this.Cabecera.add("Valor-Calculado");
        this.Cabecera.add("Diferencias");
    }
    public void getCuentAportes(){
        try {
            String Str_Sql = "select sum(cremov) as cred , sum(debmov)as deb, sum(cremov)-sum(debmov) as Neto from condat2006.movimi where fecmov>="+this.FechaIncial
                             +" and fecmov<="+this.FechaFinal
                             +" and ctamov like '410505%'";

            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(rs.next()){
               Detalle = new Vector();
               Detalle.add("410505");
               Detalle.add("Cta de Aportes");
               Detalle.add(this.JFormato.format(rs.getDouble("cred")));
               Detalle.add(this.JFormato.format(rs.getDouble("deb")));
               this.TotalIngresos = rs.getDouble("Neto");
               Detalle.add(this.JFormato.format(this.TotalIngresos));
               Detalle.add(0);
               Detalle.add(0);
               Detalle.add(0);
               Fila.add(Detalle);
            }
            this.jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cabecera));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getCuentAportes() "+e.getMessage());  
        }
    }
    public void getVlrPersonas_Mayores_Edad_19_a_23(double Vlr){
        try {
            String Str_Sql = "select * from selinlib.JFDISTRIBU where estado ='TOTAL1'";
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(rs.next()){
                String PCuenta = rs.getString("CTACON");
                String NombreCta = rs.getString("DESCRIP");
                double Porcentaje = rs.getDouble("PORCEN");
                
                Str_Sql = "select sum(cremov) as cred , sum(debmov)as deb, sum(cremov)-sum(debmov) as Neto from condat2006.movimi where fecmov>="+this.FechaIncial
                         +" and fecmov<="+this.FechaFinal
                         +" and ctamov like '"+PCuenta+"%'";
                ResultSet Rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
               if(Rs2.next()){ 
                    Detalle = new Vector();
                    Detalle.add(PCuenta);
                    Detalle.add(NombreCta);
                    Detalle.add(this.JFormato.format(Rs2.getDouble("deb")));
                    Detalle.add(this.JFormato.format(Rs2.getDouble("cred")));
                    double Valor = Rs2.getDouble("deb");
                    Detalle.add(this.JFormato.format(Valor));
                    Detalle.add(Porcentaje);
                    double Calculado = Vlr*(Porcentaje/100);
                    Detalle.add(this.JFormato.format(Calculado));
                    double Diferencia = Valor - Calculado;
                    Detalle.add(this.JFormato.format(Diferencia));
                    Fila.add(Detalle);
               }
            }
            this.jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cabecera));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getVlrPersonas_Mayores_Edad_19_a_23() "+e.getMessage());  
        }
    }
    public void getSubsidioEducacion_Ley_115(double Vlr){
                try {
            String Str_Sql = "select * from selinlib.JFDISTRIBU where estado ='TOTAL2'";
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(rs.next()){
               String PCuenta = rs.getString("CTACON").trim();  
               String NomCta = rs.getString("DESCRIP");  
               double Porcentaje =  rs.getDouble("PORCEN");  
               Str_Sql = "select sum(cremov) as cred , sum(debmov)as deb, sum(cremov)-sum(debmov) as Neto from condat2006.movimi where fecmov>="+this.FechaIncial
                             +" and fecmov<="+this.FechaFinal
                             +" and ctamov like '"+PCuenta+"%'";
              ResultSet Rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
              if(Rs2.next()){  
                        Detalle = new Vector();
                        Detalle.add(PCuenta);
                        Detalle.add(NomCta);
                        Detalle.add(this.JFormato.format(Rs2.getDouble("deb")));//Debito
                        Detalle.add(this.JFormato.format(Rs2.getDouble("cred")));//Credito
                        double RContable= Rs2.getDouble("deb");
                        Detalle.add(this.JFormato.format(RContable));//Neto
                        Detalle.add(Porcentaje);//Porcentaje
                        double Calculado  = Vlr;
                        Detalle.add( this.JFormato.format(Calculado));//Valor
                        double Diferencias = Calculado - RContable;
                        Detalle.add(this.JFormato.format(Diferencias));
                        Fila.add(Detalle);
             }
           }
            this.jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cabecera));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSubsidioEducacion_Ley_115(double Vlr) "+e.getMessage());  
        }
    }
    public void getSaldoApotes(){
        try {
            String Str_Sql = "select * from selinlib.JFDISTRIBU where estado ='DEDU1'";
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(rs.next()){
                double Porcentaje = rs.getDouble("PORCEN");
                double Calc_71 = this.TotalIngresos*(Porcentaje/100);
                Str_Sql = "select * from selinlib.JFDISTRIBU where estado ='DEDU2'";
                ResultSet rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                if(rs2.next()){
                    double XPorcentaje = rs2.getDouble("PORCEN");
                    double deduccion2 = Calc_71 *(XPorcentaje/100);
                    double Total2 = (Calc_71 -deduccion2)*0.10;
                    this.getSubsidioEducacion_Ley_115(Total2);
                } 
                getVlrPersonas_Mayores_Edad_19_a_23(Calc_71);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSaldoApotes() "+e.getMessage());  
        }
    }
    
    
    
    public void getDistribucionGeneral(){
        try {
            String Str_Sql = "select * from selinlib.JFDISTRIBU where estado ='ACTIVA'";
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(rs.next()){
               String PCuenta = rs.getString("CTACON").trim();  
               String NomCta = rs.getString("DESCRIP");  
               double Porcentaje =  rs.getDouble("PORCEN");  
               Str_Sql="select * from selinlib.JFPORCEAGR where CUENAGR='"+PCuenta.trim()+"' ";
               ResultSet resultado = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
               boolean Control=false;
               DebAgr =0; CreAgr=0;
               while(resultado.next()){
                   Control=true;
                   getMovimiento_Contable(resultado.getString("cuecon"),resultado.getString("CCOSTO"));
                   
               }
               resultado.close();
             
              Str_Sql = "select sum(cremov) as cred , sum(debmov)as deb, sum(cremov)-sum(debmov) as Neto from condat2006.movimi where fecmov>="+this.FechaIncial
                                      +" and fecmov<="+this.FechaFinal
                                      +" and ctamov like '"+PCuenta.trim()+"%'";
              
              ResultSet Rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);

              if(Rs2.next()){  
                        Detalle = new Vector();
                        Detalle.add(PCuenta);
                        Detalle.add(NomCta);
                        if(Control){
                                     Detalle.add(this.JFormato.format(DebAgr));//Debito
                                     Detalle.add(this.JFormato.format(CreAgr));//Credito
                                     double RContable= DebAgr-CreAgr;
                                     Detalle.add(this.JFormato.format(RContable));//Neto
                                     Detalle.add(Porcentaje);//Porcentaje
                                     double Calculado  = (Porcentaje/100)*this.TotalIngresos;
                                     Detalle.add( this.JFormato.format(Calculado));//Valor
                                     double Diferencias = Calculado - RContable;
                                     Detalle.add(this.JFormato.format(Diferencias));
                       }else{
                                     //System.out.println("  ++++  "+Str_Sql);
                                     Detalle.add(this.JFormato.format(Rs2.getDouble("deb")));//Debito
                                     Detalle.add(this.JFormato.format(Rs2.getDouble("cred")));//Credito
                                     double RContable= Rs2.getDouble("deb") - Rs2.getDouble("cred");
                                     Detalle.add(this.JFormato.format(RContable));//Neto
                                     Detalle.add(Porcentaje);//Porcentaje
                                     double Calculado  = (Porcentaje/100)*this.TotalIngresos;
                                     Detalle.add( this.JFormato.format(Calculado));//Valor
                                     double Diferencias = Calculado - RContable;
                                     Detalle.add(this.JFormato.format(Diferencias));
                        }
                                 
                        Fila.add(Detalle);
            }
                      Rs2.close();
           }
            
            this.jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cabecera));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getDistribucionGeneral() "+e.getMessage());  
        }
        
    }
    
    public void getMovimiento_Contable(String PCuenta, String Tiene_centro_Costo){
        try {
            String Str_Sql2="";
            if  (Tiene_centro_Costo.trim().equals("N") ) {
                Str_Sql2 = "select sum(cremov) as cred , sum(debmov)as deb, sum(cremov)-sum(debmov) as Neto from condat2006.movimi where fecmov>="+this.FechaIncial
                                      +" and fecmov<="+this.FechaFinal
                                      +" and ctamov like '"+PCuenta.trim()+"%'";
            }else{
                 Str_Sql2 = "select 51 , sum(debmov)  as deb , sum(cremov) as cred   \n" +
                            " from condat2006.movimi                  \n" +
                            " where fecmov>= "+this.FechaIncial+"  and fecmov <= " +this.FechaFinal+
                            " and ctamov like '"+PCuenta.trim()+"%' and cenmov like '"+Tiene_centro_Costo.trim()+"%' ";   
            }
            //System.out.println(""+Str_Sql2);
            ResultSet Rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql2);
            
            if(Rs2.next()){  
                       DebAgr= DebAgr+Rs2.getDouble("deb");
                       CreAgr = CreAgr+ Rs2.getDouble("cred");
                       //System.out.println("Debito "+DebAgr+" Credito "+CreAgr);
            }
            Rs2.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," getMovimiento_Contable(String PCuenta, String Tiene_centro_Costo) "+e.getMessage());  
        } 
    }
    
 public void getCuentas_Financieras(){
     try {
          String Str_Sql = "Select CTAFIN from SELINLIB.JFDISTRIBU WHERE CTAFIN <> '' AND CTACON <> 51 AND CTACON <> 6105";
          ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
          jCCuentas.addItem("");
          while(Rs.next()){      
              jCCuentas.addItem(Rs.getString("CTAFIN"));
          }
          Rs.close();
          
          
          Str_Sql= "Select CUENFIN from SELINLIB.JFDISTRAGR WHERE MARCA='A' OR MARCA ='B'"  ;
          ResultSet Rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
          while(Rs2.next()){      
              jCCuentas.addItem(Rs2.getString("CUENFIN"));
          }
          Rs2.close();
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this,"getCuentas() "+e.getMessage());  
     }
 }  
    
  public void getComboPeriodo(){
            try {
                 String Str_Sql ="select periodo from selinlib.JFDISTRPER order by periodo desc";
                 ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 jCPeriodo = new javax.swing.JComboBox();
                 jCDT_Periodo.addItem("");
                 
                 while(Rs.next()){
                     jCPeriodo.addItem(Rs.getString("periodo"));
                 
                 }
                 Rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"getComboPeriodo() "+e.getMessage());  
            }
  }    
  
  
    public void getCombo_CDTs(){
            try {
                 String Str_Sql ="select periodo from selinlib.JFDISTRPER order by periodo desc";
                 ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 jCDT_Periodo.addItem("-");
                 while(Rs.next()){
                     jCDT_Periodo.addItem(Rs.getString("periodo"));
                 }
                 Rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"getComboPeriodo() "+e.getMessage());  
            }
  }    
  
    public void getCombo_Fondos_CDTs(){
            try {
                 String Str_Sql ="select distinct cuenfin as cuenta from selinlib.JFDISTRAGR order by cuenfin asc";
                 ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 while(Rs.next()){
                     jCDT_Cuenta.addItem(Rs.getString("cuenta"));
                 }
                 Rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"getComboPeriodo() "+e.getMessage());  
            }
  }    

  
  public void setCabeceraBanco(){
     this.CabBanco.clear();
     this.CabBanco.add("Cuenta"); 
     this.CabBanco.add("Fecha"); 
     this.CabBanco.add("Numero Documento"); 
     this.CabBanco.add("Credito"); 
     this.CabBanco.add("Debito"); 
     this.CabBanco.add("Periodo"); 
  }  
  public void getInformacionBanco(String FIncial , String FFinal, String Cta){
      try {
          String Str_Sql ="select * from condat2006.movimi where fecmov>="+FIncial+" and fecmov<="+FFinal+" and"
                  + "  ctamov ='"+Cta.trim()+"'";
          System.out.println("Consulta Banco contable "+Str_Sql);
          ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
          this.FilaBanco.clear();
          while(Rs.next()){
            this.getComboPeriodo();
            this.DetBanco = new Vector();
            this.DetBanco.add(Rs.getString("ctamov"));
            this.DetBanco.add(Rs.getString("fecmov"));
            this.DetBanco.add(Rs.getString("NUMMOV"));
            this.DetBanco.add(this.JFormato.format(Rs.getDouble("cremov")));
            this.DetBanco.add(this.JFormato.format(Rs.getDouble("debmov")));
            this.DetBanco.add("");
            this.FilaBanco.add(this.DetBanco);
          } 
          Rs.close();
          
          this.jTable2.setModel(new javax.swing.table.DefaultTableModel(this.FilaBanco, this.CabBanco));
          this.jTable2.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(jCPeriodo));
          jTable2.setAutoCreateRowSorter(true);
      } catch (Exception e) {
          JOptionPane.showMessageDialog(this,"getInformacionBanco() "+e.getMessage());  
      }
  }
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDistribucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JDistribucion(null,null,null,null).setVisible(true);
            }
        });
    }
    
    private javax.swing.JComboBox jCPeriodo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jCCuentas;
    private javax.swing.JComboBox jCDT_Cuenta;
    private javax.swing.JComboBox jCDT_Estado;
    private javax.swing.JTextField jCDT_Fec_Aper;
    private javax.swing.JTextField jCDT_Fec_Cierre;
    private javax.swing.JTextField jCDT_Nro;
    private javax.swing.JComboBox jCDT_Periodo;
    private javax.swing.JTextField jCDT_Valor;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker3;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    // End of variables declaration//GEN-END:variables
}
