/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package FondosLey;

import BD_As400.JConection;
import java.io.File;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;



/**
 *
 * @author Garyn Carrillo
 */
public class JInversiones extends javax.swing.JFrame {

    /**
     * Creates new form JDistribucion
     */
     private String FechaIncial , FechaFinal;
     private String FechaMes;
     private JConection JBase_Datos;
     private Connection Cn;
     private String Usuario;
     
     private Vector Cabecera;
     private Vector Fila;
     private Vector Detalle;
     
     private Vector CabBanco;
     private Vector FilaBanco;
     private Vector DetBanco;
     
     private Vector CabBancoInsert;
     private Vector FilaBancoInsert;
     private Vector DetBancoInsert;
     
     private Vector CabConciliacion;
     private Vector FilaConciliacion;
     private Vector DetConciliacion;
     
     
     private String FechaUsuario;
     private String PPeriodo;
     private String NumeroFormato = "##############";
     private DecimalFormat JFormato ;
     private double TotalIngresos;
     
     private boolean CTabla1, CTabla2;
     
     
    public JInversiones(JConection JBase_Datos3, Connection Cn2, String Usuariox, String PPeriodo) {
        CTabla1 =  CTabla2=false;
        java.util.Date ahora = new java.util.Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyyMMdd");
        FechaUsuario =formateador.format(ahora);
        
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        this.Usuario = Usuariox;
        this.PPeriodo =PPeriodo;
        Cabecera = new Vector();
        Fila = new Vector();
        
        this.CabBanco = new Vector();
        this.FilaBanco = new Vector();
        
        this.CabBancoInsert = new Vector();
        this.FilaBancoInsert = new Vector();
        
        
        this.CabConciliacion = new Vector();
        this.FilaConciliacion = new Vector(); 
        
        this.getCabecera();
        JFormato= new DecimalFormat(NumeroFormato);
        this.CabeceraBancoInsert();
        initComponents();
        this.getCuentas_Financieras();
        this.getTablaConciliacion(this.PPeriodo);

        this.setCabecera_Conciliacion();


        jLabel2.setText("Periodo: "+this.PPeriodo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        BFechaInicial = new javax.swing.JTextField();
        BFechaFinal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCCuentas = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTFechaInicial = new javax.swing.JTextField();
        jTFechaFinal = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribucion de Fondos de Ley");

        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Fecha", "Numero Documento", "Credito", "Debito", "Periodo", "Fec. Inicial", "Fec. Final"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable2MousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton3.setText("Mover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta", "Fecha", "Numero Documento", "Credito", "Debito", "Periodo", "Fec. Inicial", "Fec. Final"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Periodo:");

        jButton10.setText("Imprimir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Ver");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Ver");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(BFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(BFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton2)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(27, 27, 27)
                                .addComponent(jButton10)))
                        .addGap(0, 378, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(BFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton10)
                    .addComponent(jButton12))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inversiones", jPanel2);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuenta Contable", "Descripcion", "Debito", "Credito", "Opr"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton7.setText("Conciliar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Imprimir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "FOVIS", "FONIÑEZ", "FOSFEC", "LEY115", "FOSYGA", "PYP", "TODOS" }));

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)
                        .addGap(45, 45, 45)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jButton8))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jTFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Conciliacion", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setCabeceraBanco();
        getInformacionBanco(this.BFechaInicial.getText().trim(),BFechaFinal.getText().trim(), jCCuentas.getSelectedItem().toString() );
        //Buscar_Movimiento_Fosyga(this.BFechaInicial.getText().trim() , BFechaFinal.getText().trim(), "28521501", "900462447" );
    }//GEN-LAST:event_jButton2ActionPerformed
    public void CabeceraBancoInsert(){
        this.CabBancoInsert.add("Cuenta");
        this.CabBancoInsert.add("Fecha");
        this.CabBancoInsert.add("Numero Documento");
        this.CabBancoInsert.add("Credito");
        this.CabBancoInsert.add("Debito");
        this.CabBancoInsert.add("Periodo");
        this.CabBancoInsert.add("Fec. Inicial");
        this.CabBancoInsert.add("Fec. Final");
        
    }
    public void setMover(){
        
        this.DetBancoInsert = new Vector();
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 6).toString());
        this.DetBancoInsert.add(jTable2.getValueAt(jTable2.getSelectedRow(), 7).toString());
        
        this.FilaBancoInsert.add(DetBancoInsert);
        this.jTable3.setModel(new javax.swing.table.DefaultTableModel(this.FilaBancoInsert, this.CabBancoInsert));
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       try{
           if ( !jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString().trim().equals("")){
                 this.setMover();
           }else{
                    JOptionPane.showMessageDialog(this,"Debe Seleccionar el periodo al cual desea conciliar ");
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"ClickButton() "+e.getMessage() );
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (! this.Guardar()){
            JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente " );
        }else{
            JOptionPane.showMessageDialog(this,"Se Guardo Correctamente " );
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setBorrarFila_tabla3();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.FechaIncial = this.jTFechaInicial.getText();
        this.FechaFinal = this.jTFechaFinal.getText();
        getSaldoFovis();
        getSaldoFoniñez();
        getSaldoFosfec();
        getSaldoFosyga();
        getSaldoLey_115();
        getSaldoPromocion_Prevencion();
//        if( this.getConciliar()){
//            this.getInformacion_Conciliacion();
//            JOptionPane.showMessageDialog(this,"Se Guardo Correctamente  "); 
//        }else{
//            JOptionPane.showMessageDialog(this,"No se Pudo Guardar Correctamente  "); 
//        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      
//      if( !(jTFechaInicial.getText().trim().equals(""))  &&!(jTFechaFinal.getText().trim().equals(""))){
//            JJasper  GenPdf = new JJasper();
//            GenPdf.setTipo(1);
//            GenPdf.setFechaInicial(jTFechaInicial.getText().trim());
//            GenPdf.setFechaFinal(jTFechaFinal.getText().trim());
//            GenPdf.setPPeriodo(PPeriodo);
//            GenPdf.setConeccion(Cn);
//            GenPdf.start();
//      }else{
//          JOptionPane.showMessageDialog(this,"Debe diligenciar la fecha inicial y fecha Final en la Primera pestaña  "); 
//      }
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
            JJasper  GenPdf = new JJasper();
            GenPdf.setTipo(3);
            GenPdf.setPPeriodo(PPeriodo);
            GenPdf.setConeccion(Cn);
            GenPdf.start();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MousePressed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
             String PFecha = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
             String PNumDoc = jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString();
             String PCuenta = jTable2.getValueAt(jTable2.getSelectedRow(), 0).toString();
             JDetalleContable Frm_JDetalleContable =  new JDetalleContable(this.JBase_Datos, this.Cn, PFecha, PNumDoc, PCuenta);
             Frm_JDetalleContable.setVisible(true);       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," Frm_Detalle()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            String PFecha = jTable3.getValueAt(jTable3.getSelectedRow(), 1).toString();
            String PNumDoc = jTable3.getValueAt(jTable3.getSelectedRow(), 2).toString();
            String PCuenta = jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString();
            JDetalleContable Frm_JDetalleContable =  new JDetalleContable(this.JBase_Datos, this.Cn, PFecha, PNumDoc, PCuenta);
            Frm_JDetalleContable.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," Frm_Detalle()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getConciliacion();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void setCabecera_Conciliacion(){
        this.CabConciliacion.add("Cuenta Contable");
        this.CabConciliacion.add("Descripcion");
        this.CabConciliacion.add("Debito");
        this.CabConciliacion.add("Credito");
        this.CabConciliacion.add("Opr");
    }
    public void getConciliacion(){
           try{
                String Fondo = jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).toString();
                if(!Fondo.trim().equals("TODOS")){
                    this.FilaConciliacion.clear();
                    String Str_Sql ="Select * from SELINLIB.JFSALDOINI where NCUENTA= '"+Fondo.trim()+"' AND TIPO=1 AND PERIODO="+this.PPeriodo+" ORDER BY CUENTA DESC";
                    ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                    
                    double Debito =0;
                    double Credito =0;
                    
                    double Conciliacion =0;
                    while(Rs.next()){
                            this.DetConciliacion = new Vector();
                            this.DetConciliacion.add(Rs.getString("CUENTA"));
                            this.DetConciliacion.add(Rs.getString("NCUENTA"));
                            Debito = Rs.getDouble("DEBITO");
                            Credito = Rs.getDouble("CREDITO");
                            this.DetConciliacion.add(this.JFormato.format(Debito));
                            this.DetConciliacion.add(this.JFormato.format(Credito));
                            String Operacion = Rs.getString("OPR");
                            this.DetConciliacion.add(Operacion);
                            this.FilaConciliacion.add(this.DetConciliacion);     
                            if(Operacion.trim().equals("+")){
                                Conciliacion = Conciliacion +(Debito-Credito);
                            }else{
                                Conciliacion = Conciliacion -(Debito-Credito);
                            }
                    }

                    Rs.close();
                    
                    Str_Sql="SELECT * FROM SELINLIB.JFSALEQUIV AS T1 , SELINLIB.JFSBANCO AS T2  " +
                            " WHERE NFONDO='"+Fondo+"' AND T1.CUEBAN =  T2.CUENTA AND PERIODO = "+this.PPeriodo;
                    ResultSet Rs2 = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);


                    while(Rs2.next()){
                            this.DetConciliacion = new Vector();
                            this.DetConciliacion.add(Rs2.getString("CUEBAN"));
                            this.DetConciliacion.add(Rs2.getString("NCUEBAN"));
                            Debito  = Rs2.getDouble("DEBITO");
                            Credito = Rs2.getDouble("CREDIT");
                            this.DetConciliacion.add(this.JFormato.format(Debito));
                            this.DetConciliacion.add(this.JFormato.format(Credito));
                            this.DetConciliacion.add("+");
                            this.FilaConciliacion.add(this.DetConciliacion);     
                            Conciliacion = Conciliacion +(Debito-Credito);
                    }
                    
                    this.DetConciliacion = new Vector();
                    this.DetConciliacion.add("TOTAL PARCIAL ");
                    this.DetConciliacion.add("-->>  ");
                    this.DetConciliacion.add(this.JFormato.format(Conciliacion));
                    this.DetConciliacion.add(0);
                    this.DetConciliacion.add("-----");
                    this.FilaConciliacion.add(this.DetConciliacion);     
                    this.jTable4.setModel(new javax.swing.table.DefaultTableModel(this.FilaConciliacion, this.CabConciliacion));
                    
                    Rs2.close();
                }else{

                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this," Buscar_Fondo_Button  "+e.getMessage()); 
        }
    } 
    public void getSaldoFovis(){
        try {
               //Limpiar Registro para conciliar
               String Str_Sql = "delete from selinlib.jfsaldoini where periodo="+this.PPeriodo; 
               boolean  Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               //int Fec = Integer.parseInt(this.PPeriodo)-1;
               //String FechaD = Fec+""+"31";
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '18109502', 'FOVIS',"+this.PPeriodo+" , 1, sum(debmov) - sum(cremov) as Total, 0 ,'+' from condat2006.movimi where ctamov like '18109502 %' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
            
               
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '181005', 'FOVIS',"+this.PPeriodo+" , 1, sum(debmov) - sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '181005 %' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2851', 'FOVIS',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2851%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2861', 'FOVIS',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2861%' "
                    + " and fecmov>=20090101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSaldoFovis() "+e.getMessage() );
        }
    }
    
     public void getSaldoFoniñez(){
        try {
            
               String Str_Sql ="insert into selinlib.jfsaldoini "+" select '181020', 'FONIÑEZ',"+this.PPeriodo+" , 1, sum(debmov) - sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '181020 %' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               boolean Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
                             
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '18109504', 'FONIÑEZ',"+this.PPeriodo+" , 1, sum(debmov) - sum(cremov) as Total, 0 ,'+' from condat2006.movimi where ctamov like '18109504 %' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);        
               
               //ITROS
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2854', 'FONIÑEZ',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2854%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2864', 'FONIÑEZ',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2864%' "
                    + " and fecmov>=20090101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSaldoFoniñez() "+e.getMessage() );
        }
    }
     public void getSaldoFosfec(){
        try {
               String Str_Sql ="insert into selinlib.jfsaldoini "+" select '181035', 'FOSFEC',"+this.PPeriodo+" , 1, sum(debmov) - sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '181035 %' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               boolean Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               //////////////////
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '18109503', 'FOSFEC',"+this.PPeriodo+" , 1, sum(debmov)-sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '18109503 %' "
                    + " and fecmov>=20090101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2858', 'FOSFEC',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2858%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
//               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2859', 'FOSFEC',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2859%' "
//                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
//               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
//               
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2868', 'FOSFEC',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2868%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSaldoFosfec() "+e.getMessage() );
        }
    }
     
    public void getSaldoLey_115(){
        try {
               String Str_Sql ="insert into selinlib.jfsaldoini "+" select '181015', 'LEY115',"+this.PPeriodo+" , 1, sum(debmov) - sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '181015 %' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               boolean Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               ///////////////////////////
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '18109506', 'LEY115',"+this.PPeriodo+" , 1, sum(debmov)-sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '18109506 %' "
                    + " and fecmov>=20090101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2853', 'LEY115',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2853%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2863', 'LEY115',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2863%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSaldoLey_115() "+e.getMessage() );
        }
    } 
     
    public void getSaldoFosyga(){
        try {
               String Str_Sql ="insert into selinlib.jfsaldoini "+" select '2852', 'FOSYGA',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2852%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               boolean Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               ///////////////////////////
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '18109507', 'FOSYGA',"+this.PPeriodo+" , 1, sum(debmov)-sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '18109507 %' "
                    + " and fecmov>=20090101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2862', 'FOSYGA',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2862%' "
                    + " and fecmov>=20080601 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," getSaldoFosyga()"+e.getMessage() );
        }
    } 
    
    public void getSaldoPromocion_Prevencion(){
        try {
               String Str_Sql ="insert into selinlib.jfsaldoini "+" select '181010', 'PYP',"+this.PPeriodo+" , 1, sum(debmov)-sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '181010 %' "
                    + " and fecmov>=20000101 and fecmov <="+this.FechaFinal;
               boolean Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 

               Str_Sql ="insert into selinlib.jfsaldoini "+" select '18109505', 'PYP',"+this.PPeriodo+" , 1, sum(debmov)-sum(cremov) as Total, 0,'+' from condat2006.movimi where ctamov like '18109505 %' "
                    + " and fecmov>=20090101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2857', 'PYP',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2857%' "
                    + " and fecmov>=20100101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
               Str_Sql ="insert into selinlib.jfsaldoini "+" select '2856', 'PYP',"+this.PPeriodo+" , 1, sum(cremov)-sum(debmov) as Total, 0,'-' from condat2006.movimi where ctamov like '2856%' "
               + " and fecmov>=19900101 and fecmov <="+this.FechaFinal;
               Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getSaldoPromocion_Prevencion() "+e.getMessage() );
        }
    } 
    
    
    
   
    

    
    public void setAnchoColumnas_Tabla4(){
        jTable4.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable4.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTable4.getColumnModel().getColumn(2).setPreferredWidth(230);
        jTable4.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTable4.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTable4.getColumnModel().getColumn(5).setPreferredWidth(10);
        jTable4.getColumnModel().getColumn(6).setPreferredWidth(10);
    }
    
    public boolean getExiste_Distribucion(String Cuenta , String Periodo){
        boolean Control = false;
        try {
            String Str_Sql =" select * from selinlib.JFDISTRCAB where Ctacon="+Cuenta+" and Periodo="+Periodo;
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(Rs.next()){
                Control=true;
            }
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getExiste_Distribucion()  "+e.getMessage()); 
        }
        
        return Control;
    }

    
    
   
    
     
    public boolean EliminaDetalle(){
        boolean Rs=false;
        try {
                String Cuenta = jTable3.getValueAt(this.jTable3.getSelectedRow(), 0).toString();
                String Fecha = jTable3.getValueAt(this.jTable3.getSelectedRow(), 1).toString();
                String NumDocumento = jTable3.getValueAt(this.jTable3.getSelectedRow(), 2).toString();
                String Periodo = jTable3.getValueAt(this.jTable3.getSelectedRow(), 5).toString();
                String Str_Sql = "delete from selinlib.JFSBANCO where fecha="+Fecha+" and numdoc="+NumDocumento+
                    " and periodo="+Periodo+" and cuenta="+Cuenta;    
                Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"EliminaDetalle()  "+e.getMessage()); 
        }
        return Rs;
    }
    
    public void setBorrarFila_tabla3(){
       try{ 
            if (EliminaDetalle()){
                DefaultTableModel Modelo =(DefaultTableModel) jTable3.getModel();
                Modelo.removeRow(jTable3.getSelectedRow());
                jTable3.updateUI();
            }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"El registro seleccionado debe Contener informacion"); 
       }
    }
    
    
    public boolean getExiste(String NumDocumento, String Periodo, String Cuenta, String Fecha){
        boolean Control = false;
        try {
            String Str_Sql = "select * from selinlib.JFSBANCO where fecha="+Fecha+" and numdoc="+NumDocumento+
                    " and periodo="+Periodo+" and cuenta="+Cuenta;    
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(Rs.next()){
                Control=true;
            }
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getExiste() "+e.getMessage() );
        }
        return Control;
    }
    public void getTablaConciliacion(String Periodo){
        try {
            String Str_Sql = "select * from selinlib.JFSBANCO where Periodo="+Periodo;
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(Rs.next()){
                DetBancoInsert = new Vector();
                DetBancoInsert.add(Rs.getInt("Cuenta"));
                DetBancoInsert.add(Rs.getInt("Fecha"));
                DetBancoInsert.add(Rs.getInt("Numdoc"));
                DetBancoInsert.add(Rs.getInt("Credit"));
                DetBancoInsert.add(Rs.getInt("Debito"));
                DetBancoInsert.add(Rs.getInt("Periodo"));
                DetBancoInsert.add(Rs.getInt("Fecini"));
                DetBancoInsert.add(Rs.getInt("Fecfin"));
                FilaBancoInsert.add(DetBancoInsert);
            }
            this.jTable3.setModel(new javax.swing.table.DefaultTableModel(this.FilaBancoInsert, this.CabBancoInsert));
            Rs.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getTablaConciliacion() "+e.getMessage() );
        }
    }
    
    public boolean Guardar(){
        boolean Rs=false;
        try {
            int Cantidad =  jTable3.getRowCount();
            for (int i = 0; i < Cantidad; i++) {
                String Cuenta = jTable3.getValueAt(i, 0).toString();
                String Fecha = jTable3.getValueAt(i, 1).toString();
                String NumDocumento = jTable3.getValueAt(i, 2).toString();
                double Credito = Double.valueOf( jTable3.getValueAt(i, 3).toString());
                double Debito = Double.valueOf( jTable3.getValueAt(i, 4).toString());
                String Periodo = jTable3.getValueAt(i, 5).toString();
                String FecInicial = jTable3.getValueAt(i, 6).toString();
                String FecFinal = jTable3.getValueAt(i, 7).toString();

                if (!this.getExiste(NumDocumento, Periodo, Cuenta, Fecha)){
                    String Str_Sql ="insert into selinlib.JFSBANCO"
                                    + " VALUES("+Cuenta+" , "+Periodo+" , "+Fecha+" , "+NumDocumento+" , "+Debito+" , "
                                    + ""+Credito+", '"+this.Usuario+"',"+FechaUsuario+","+FecFinal+","+FecFinal+")";
                     Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                     if(Rs==false){
                           JOptionPane.showMessageDialog(this,"No se pudo insertar " ); 
                     }
                }else{
                    String Str_Sql ="update selinlib.JFSBANCO"
                                    + " set Debito="+Debito
                                    + ", Credit="+Credito
                                    + ", Usuari='"+Usuario+"' "
                                    + ", Fecusu="+FechaUsuario
                                    + ", Fecini="+FecInicial
                                    + ", Fecfin="+FecFinal
                                    + " where fecha="+Fecha+" and Periodo="+Periodo+" and Cuenta="+Cuenta+" and numdoc="+NumDocumento;
                     Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
                     if(Rs==false){
                           JOptionPane.showMessageDialog(this,"No se pudo Actualizar " ); 
                     }
                }
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Guardar() "+e.getMessage() );
        }
        return Rs;
    }
    public void getCabecera(){
        this.Cabecera.add("Cuenta Sistema");
        this.Cabecera.add("Cta Aportes");
        this.Cabecera.add("Debito-Contable");
        this.Cabecera.add("Credito-Contable");
        this.Cabecera.add("Neto-Contable");
        this.Cabecera.add("Porcentaje");
        this.Cabecera.add("Valor-Calculado");
        this.Cabecera.add("Diferencias");
    }

 public void getCuentas_Financieras(){
     try {
          String Str_Sql = "Select CUENTA from SELINLIB.JFSALDOCTA WHERE MUESTRA='CI' ";
          ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
          jCCuentas.addItem("");
          while(Rs.next()){      
              jCCuentas.addItem(Rs.getString("CUENTA"));
          }
     } catch (Exception e) {
         JOptionPane.showMessageDialog(this,"getCuentas() "+e.getMessage());  
     }
 }  
    
  public void getComboPeriodo(){
            try {
                 String Str_Sql ="select periodo from selinlib.JFDISTRPER order by periodo";
                 ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                 jCPeriodo = new javax.swing.JComboBox();
                 jCPeriodo.addItem("");
                 while(Rs.next()){
                     jCPeriodo.addItem(Rs.getString("periodo"));
                 }
                 Rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"getComboPeriodo() "+e.getMessage());  
            }
  }    
  public void setCabeceraBanco(){
     this.CabBanco.clear();
     this.CabBanco.add("Cuenta"); 
     this.CabBanco.add("Fecha"); 
     this.CabBanco.add("Numero Documento"); 
     this.CabBanco.add("Credito"); 
     this.CabBanco.add("Debito"); 
     this.CabBanco.add("Periodo"); 
     this.CabBanco.add("Fec. Inicial"); 
     this.CabBanco.add("Fec. Final"); 
  }  
  public void getInformacionBanco(String FIncial , String FFinal, String Cta){
      try {
          String Str_Sql ="select * from condat2006.movimi where fecmov>="+FIncial+" and fecmov<="+FFinal+" and"
                  + "  ctamov ='"+Cta.trim()+"'";
          
          ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
          this.FilaBanco.clear();
          while(Rs.next()){
            this.getComboPeriodo();
            this.DetBanco = new Vector();
            this.DetBanco.add(Rs.getString("ctamov"));
            this.DetBanco.add(Rs.getString("fecmov"));
            this.DetBanco.add(Rs.getString("NUMMOV"));
            this.DetBanco.add(this.JFormato.format(Rs.getDouble("cremov")));
            this.DetBanco.add(this.JFormato.format(Rs.getDouble("debmov")));
            this.DetBanco.add("");
            this.DetBanco.add("");
            this.DetBanco.add("");
            this.FilaBanco.add(this.DetBanco);
          } 
          Rs.close();
          
          this.jTable2.setModel(new javax.swing.table.DefaultTableModel(this.FilaBanco, this.CabBanco));
          this.jTable2.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(jCPeriodo));
          jTable2.setAutoCreateRowSorter(true);
      } catch (Exception e) {
          JOptionPane.showMessageDialog(this,"getInformacionBanco() "+e.getMessage());  
      }
  }
    

    
    
    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JInversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JInversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JInversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JInversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JInversiones(null,null,null,null).setVisible(true);
            }
        });
    }
    
    private javax.swing.JComboBox jCPeriodo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BFechaFinal;
    private javax.swing.JTextField BFechaInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jCCuentas;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFechaFinal;
    private javax.swing.JTextField jTFechaInicial;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
