/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Subsidio.Liqu;

import BD_As400.JConection;
import Subsidio.JJasper_Sub;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

/**
 *
 * @author GACA1186
 */
public class JHijosSimilitud extends javax.swing.JFrame {
    
    /**
     * Creates new form JHijosSimilitud
     */
    private Vector PCab, PFila, PDet;
    private JConection JBase_Datos;
    private Connection Cn;   
    private Vector Cab, Fila, Det;
    private Vector  Fila2, Det2;
    private Vector  PFila3, PDet3;
    
    public JHijosSimilitud(JConection JBase_Datos3, Connection Cn2) {
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        PCab = new Vector();
        PFila = new Vector();
        Cab = new Vector();
        Fila = new Vector();
        Fila2 = new Vector();
        PFila3 = new Vector();
        Cab.add("Primer Apellido");
        Cab.add("Segundo Apellido");
        Cab.add("Primer Nombre");
        Cab.add("Segundo Nombre ");
        Cab.add("Fecha de nacimiento");
        
        PCab.add("Doc. Trabajador");
        PCab.add("Doc. Hijo");
        PCab.add("Nombre del Hijo");
        PCab.add("Periodo ");
        PCab.add("Fecha ");
        PCab.add("Valor ");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Primer Apellido", "Segundo Apellido", "Primer Nombre", "Fecha de Nacimieto", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Imprimir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Similitud Hijos", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Primer Apellido", "Segundo Apellido", "Primer Nombre", "Fecha de Nacimieto", "Cantidad"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Ejecutar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Imprimir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Similitud de Padres", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc. Trabajador", "Doc. Hijo", "Nombre del Hijo", "Periodo", "Fecha", "Valor"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton3.setText("Ejecutar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("Imprimir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Liq hijos", jPanel3);

        jButton4.setText("Ejecutar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doc. Trabajador", "Doc. Hijo", "Nombre del Hijo", "Periodo", "Fecha", "Valor"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jButton8.setText("Imprimir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Liq Padres", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getHijos_Similitud();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        getPadres_similitud();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.getSimilitudLiquidacion(this.jTextField1.getText().trim(), this.jTextField2.getText().trim());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        getSimilitudLiquidacion_Padres(jTextField3.getText().trim(), jTextField4.getText().trim());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            JJasper_Sub GenPdf = new JJasper_Sub();
            GenPdf.setTipo(9);
            GenPdf.setConeccion(Cn);
            GenPdf.start();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
            JJasper_Sub GenPdf = new JJasper_Sub();
            GenPdf.setTipo(10);
            GenPdf.setConeccion(Cn);
            GenPdf.start();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
            JJasper_Sub GenPdf = new JJasper_Sub();
            GenPdf.setTipo(11);
            GenPdf.setFechaInicial(jTextField1.getText().trim());
            GenPdf.setFechaFinal(jTextField2.getText().trim());
            GenPdf.setConeccion(Cn);
            GenPdf.start();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        JJasper_Sub GenPdf = new JJasper_Sub();
        GenPdf.setTipo(12);
        GenPdf.setFechaInicial(jTextField3.getText().trim());
        GenPdf.setFechaFinal(jTextField4.getText().trim());
        GenPdf.setConeccion(Cn);
        GenPdf.start();
    }//GEN-LAST:event_jButton8ActionPerformed
    public void getHijos_Similitud(){
         try {
            String Str_Sql =" select                                                             \n" +
                            "t1.hijap1 , t1.hijap2 ,t1.hijno1 ,t1.hijno2 , t1.hijfnc  , count(*) \n" +
                            "       from subsilib.mhijos as t1                                  \n" +
                            "         ,    subsilib.mhijos as t2                                \n" +
                            "         where t1.hijdoc <> t2.hijdoc and t1.hijap1 =t2.hijap2     \n" +
                            "         and t1.hijap2 = t2.hijap2 and t1.hijno1 =t2.hijno1        \n" +
                            "         and t1.hijno2 = t2.hijno2  and t1.hijfnc = t2.hijfnc      \n" +
                            "          group by t1.hijap1 , t1.hijap2 ,                         \n" +
                            "                   t1.hijno1 , t1.hijno2  , t1.hijfnc ,            \n" +
                            "                   t2.hijap1 , t2.hijap2 ,                         \n" +
                            "                   t2.hijno1 , t2.hijno2  , t2.hijfnc              \n" +
                            "          having count(*)>1                                        ";
             
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            Fila.clear();
            while(rs.next()){
                Det= new Vector();
                Det.add(rs.getString("hijap1"));
                Det.add(rs.getString("hijap2"));
                Det.add(rs.getString("hijno1"));
                Det.add(rs.getString("hijno2"));
                Det.add(rs.getString("hijfnc"));
                Fila.add(Det);
            }
            jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cab));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage());
        }
    }

public void getSimilitudLiquidacion_Padres(String FechaInici, String FechaFin){
        try {
            String Str_Sql = "select pctliq , pdbliq ,tx3.padnom, pvaliq , ppeliq, pfeliq        \n" +
                            "     from subsilib.liquipag as tx1 ,                                \n" +
                            "    ( select                                                        \n" +
                            " t1.padap1 , t1.padap2 ,t1.padno1 ,t1.padno2 , t1.padfnc  , count(*)\n" +
                            "        from subsilib.mpadres as t1                                 \n" +
                            "          ,    subsilib.mpadres as t2                               \n" +
                            "          where t1.paddoc <> t2.paddoc and t1.padap1 =t2.padap2     \n" +
                            "          and t1.padap2 = t2.padap2 and t1.padno1 =t2.padno1        \n" +
                            "          and t1.padno2 = t2.padno2  and t1.padfnc = t2.padfnc      \n" +
                            "           group by t1.padap1 , t1.padap2 ,                         \n" +
                            "                    t1.padno1 , t1.padno2  , t1.padfnc ,            \n" +
                            "                    t2.padap1 , t2.padap2 ,                         \n" +
                            "                    t2.padno1 , t2.padno2  , t2.padfnc              \n" +
                            "           having count(*)>1                                        \n" +
                            "        ) as tx2 , subsilib.mpadres tx3                             \n" +
                            "where tx1.pdbliq = tx3.paddoc and tx1.pctliq = tx3.tradoc           \n" +
                            "and tx3.padno1 = tx2.padno1 and tx3.padno2 =tx2.padno2             "
                            +" and tx3.padap1 = tx2.padap1 and tx3.padap2=tx2.padap2  \n" +
                            "and tx3.padfnc = tx2.padfnc                            \n" +
                            "and tx1.pfeliq >= "+FechaInici+" and tx1.pfeliq<="+FechaFin
                            +" order by tx2.padno1 , tx2.padno2 , tx2.padap1, tx2.padap2 "; 
            
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            PFila3.clear();
            while(rs.next()){
                System.out.println("ENTRO ACA");
                PDet3 = new Vector();
                PDet3.add(rs.getString("pctliq"));
                PDet3.add(rs.getString("pdbliq"));
                PDet3.add(rs.getString("padnom"));
                PDet3.add(rs.getString("ppeliq"));
                PDet3.add(rs.getString("pfeliq"));
                PDet3.add(rs.getString("pvaliq"));
                PFila3.add(PDet3);
            }
            jTable4.setModel(new javax.swing.table.DefaultTableModel(PFila3, PCab));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage());
        }
    }

    
    public void getSimilitudLiquidacion(String FechaInici, String FechaFin){
        try {
            String Str_Sql ="select pctliq , pdbliq ,tx3.hijnom, pvaliq , ppeliq, pfeliq         \n" +
                            "     from subsilib.liquipag as tx1 ,                                \n" +
                            "    ( select                                                        \n" +
                            " t1.hijap1 , t1.hijap2 ,t1.hijno1 ,t1.hijno2 , t1.hijfnc  , count(*)\n" +
                            "        from subsilib.mhijos as t1                                  \n" +
                            "          ,    subsilib.mhijos as t2                                \n" +
                            "          where t1.hijdoc <> t2.hijdoc and t1.hijap1 =t2.hijap2     \n" +
                            "          and t1.hijap2 = t2.hijap2 and t1.hijno1 =t2.hijno1        \n" +
                            "          and t1.hijno2 = t2.hijno2  and t1.hijfnc = t2.hijfnc      \n" +
                            "           group by t1.hijap1 , t1.hijap2 ,                         \n" +
                            "                    t1.hijno1 , t1.hijno2  , t1.hijfnc ,            \n" +
                            "                    t2.hijap1 , t2.hijap2 ,                         \n" +
                            "                    t2.hijno1 , t2.hijno2  , t2.hijfnc              \n" +
                            "           having count(*)>1                                        \n" +
                            "        ) as tx2 , subsilib.mhijos tx3                              \n" +
                            "where tx1.pdbliq = tx3.hijdoc and tx1.pctliq = tx3.tradoc           \n" +
                            "and tx3.hijno1 = tx2.hijno1 and tx3.hijno2 =tx2.hijno2              "+
                            "and tx3.hijap1 = tx2.hijap1 and tx3.hijap2=tx2.hijap2\n" +
                            "and tx3.hijfnc = tx2.hijfnc                          \n" +
                            "and tx1.pfeliq >= "+FechaInici+" and tx1.pfeliq<=  "+FechaFin
                            +" order by tx1.pctliq  , tx1.pdbliq";    
            
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            PFila.clear();
            while(rs.next()){
                PDet = new Vector();
                PDet.add(rs.getString("pctliq"));
                PDet.add(rs.getString("pdbliq"));
                PDet.add(rs.getString("hijnom"));
                PDet.add(rs.getString("ppeliq"));
                PDet.add(rs.getString("pfeliq"));
                PDet.add(rs.getString("pvaliq"));
                PFila.add(PDet);
            }
            jTable3.setModel(new javax.swing.table.DefaultTableModel(PFila, PCab));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage());
        }
    }
    
    public void getPadres_similitud(){
         try {
            String Str_Sql ="select                                                             \n" +
                            "t1.padap1 , t1.padap2 ,t1.padno1 ,t1.padno2 , t1.padfnc  , count(*)\n" +
                            "       from subsilib.mpadres as t1                                 \n" +
                            "         ,    subsilib.mpadres as t2                               \n" +
                            "         where t1.paddoc <> t2.paddoc and t1.padap1 =t2.padap2     \n" +
                            "         and t1.padap2 = t2.padap2 and t1.padno1 =t2.padno1        \n" +
                            "         and t1.padno2 = t2.padno2  and t1.padfnc = t2.padfnc      \n" +
                            "          group by t1.padap1 , t1.padap2 ,                         \n" +
                            "                   t1.padno1 , t1.padno2  , t1.padfnc ,            \n" +
                            "                   t2.padap1 , t2.padap2 ,                         \n" +
                            "                   t2.padno1 , t2.padno2  , t2.padfnc              \n" +
                            "          having count(*)>1                                        ";
            
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            Fila2.clear();
            while(rs.next()){
                Det2= new Vector();
                Det2.add(rs.getString("padap1"));
                Det2.add(rs.getString("padap2"));
                Det2.add(rs.getString("padno1"));
                Det2.add(rs.getString("padno2"));
                Det2.add(rs.getString("padfnc"));
                Fila2.add(Det2);
            }
            jTable2.setModel(new javax.swing.table.DefaultTableModel(Fila2, Cab));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JHijosSimilitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JHijosSimilitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JHijosSimilitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JHijosSimilitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JHijosSimilitud(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
