package Auditoria;


import Principal.JLeeFichero;
import Auditoria.TipoAsignacion_Por_Mes_Periodo;
import BD_Auditoria.JConeccion_AudiSys;
import Riesgos.MapaRiesgo;
import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AplicacionAudiSys.java
 *
 * Created on 10/11/2011, 11:51:27 AM
 */
/**
 *
 * @author GACA1186 (Garyn Jairo Carrillo Caballero-2012)
 */
public class AplicacionAudiSys extends javax.swing.JFrame {
    private String[] args;
    private String RutaLogo ;
    private JLeeFichero Rl;
    private JConeccion_AudiSys JBase_Datos;
    private Connection Connection_BD;
    private String Usuario;
    
    /** Creates new form AplicacionAudiSys */
    public AplicacionAudiSys(String XUsuario){
        initComponents();
        Rl = new JLeeFichero();
        Rl.Leer();
        this.Usuario = XUsuario;
        this.RutaLogo = Rl.getLogo();
        jLabel1.setIcon(new javax.swing.ImageIcon(this.RutaLogo));
        JBase_Datos = new JConeccion_AudiSys ();
     	Connection_BD = JBase_Datos.Open_BD(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Principal");
        setBounds(new java.awt.Rectangle(150, 85, 0, 0));

        jInternalFrame1.setVisible(true);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Auditoria");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Planeacion");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Priorizacion");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Asignacion de Recursos");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Ejecucion");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Seleccion");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Monitoreo");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Por Recursos/ Por Meses");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Seguimiento de Informes");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Interfaz");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cargar Mapas de Riesgo");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Cargar Plan de años anteriores");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo_Peq.jpg"))); // NOI18N

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jMenu1.setText("Auditoria");

        jMenuItem1.setText("Asignacion de Recursos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Seguimientos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Interfaz");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
// TODO add your handling code here:
  try{  
    if (evt.getClickCount() == 2) {
        //Menu de Planeacion
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Auditoria, Planeacion, Priorizacion]") ){
             JPriorizacion Pr = new JPriorizacion(this.JBase_Datos, this.Connection_BD);
             Pr.setVisible(true);
        }
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Auditoria, Planeacion, Asignacion de Recursos]") ){
            //TipoAsignacion Tp = new TipoAsignacion();
            TipoAsignacion_Por_Mes_Periodo Tp = new TipoAsignacion_Por_Mes_Periodo(this.JBase_Datos, this.Connection_BD, this.Usuario);
            Tp.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            Tp.setVisible(true);
        }
        //Menu de Interfaz
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Interfaz, Cargar Mapas de Riesgo]") ){
            JTaller Taller = new JTaller(this.JBase_Datos, this.Connection_BD);
        }
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Auditoria, Monitoreo, Por Recursos/ Por Meses]") ){
           AuditoriaRecursos Ar= new AuditoriaRecursos (this.JBase_Datos, this.Connection_BD);
           Ar.setVisible(true);
        }
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Auditoria, Monitoreo, Seguimiento de Informes]") ){
            JSeguimientos Frm_Seguimiento =  new JSeguimientos(this.JBase_Datos , this.Connection_BD);
            Frm_Seguimiento.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
            Frm_Seguimiento.setVisible(true);
        }
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Auditoria, Ejecucion, Seleccion]") ){
           InformeSelecion Is= new InformeSelecion (this.JBase_Datos, this.Connection_BD, this.Usuario);
           Is.setBounds(10,10,1200, 600);
           Is.setVisible(true);
        }
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Mapa de Riesgo, Construccion]") ){
            MapaRiesgo Mr = new MapaRiesgo ();
            Mr.setVisible(true);
        }
        if ( jTree1.getSelectionModel().getSelectionPath().toString().trim().equals("[root, Mapa de Riesgo, Seguimiento]") ){
        }
        
        System.out.println(jTree1.getSelectionModel().getSelectionPath().toString().trim());
    }
  }catch(Exception e ){}
}//GEN-LAST:event_jTree1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        if(Connection_BD!=null){
            this.JBase_Datos.Close_BD(Connection_BD);
        }
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(Connection_BD!=null){
            this.JBase_Datos.Close_BD(Connection_BD);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TipoAsignacion_Por_Mes_Periodo Tp = new TipoAsignacion_Por_Mes_Periodo(this.JBase_Datos, this.Connection_BD, this.Usuario);
        Tp.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Tp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JSeguimientos Frm_Seguimiento =  new JSeguimientos(this.JBase_Datos , this.Connection_BD);
        Frm_Seguimiento.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        Frm_Seguimiento.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacionAudiSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacionAudiSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacionAudiSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacionAudiSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AplicacionAudiSys(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
