package Auditoria;


import BD_Auditoria.JConeccion_AudiSys;
import ReporteAuditoria.*;
import java.sql.*;
import javax.swing.*;
import java.util.Date;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformeAuditoria.java
 *
 * Created on 7/03/2012, 05:54:30 PM
 */
/**
 *
 * @author GACA1186 (Garyn Jairo Carrillo Caballero-2012)
 */
public class InformeAuditoria extends javax.swing.JFrame {
    private boolean Estado ;
    private String IdentificadorPlanAuditoria;
    private Object [] Cabecera ;
    private Object [] [] Detalle  ;
    private String Usuario;
    private JConeccion_AudiSys JBase_Datos;
    private Connection Connection_BD;
    
    /** Creates new form InformeAuditoria */
    public InformeAuditoria(JConeccion_AudiSys JBase_Datos, Connection Connection_BD,String IdPlan, String XUsuario, int Tipo) {
        this.JBase_Datos = JBase_Datos;
        this.Connection_BD = Connection_BD;  
        this.Usuario = XUsuario;
        Cabecera =  new Object [3];
        Detalle  =  new Object [50][3];
        initComponents();
        jTextArea5.setText("Este informe fue comentado con el señor, XXXX , Cargo , quien manifesto estar de acuerdo con lo expresado en el anterior informe.");
        jTable1.setAutoResizeMode(5);
        jPanel6.setVisible(false);
        Estado = false;
        this.IdentificadorPlanAuditoria = IdPlan;
        if(Tipo==2){
            this.IdentificadorPlanAuditoria = getBuscarCodigPlan(IdPlan);
        }
        this.getDivisiones();
        this.getTipoInforme();
        this.CargarAuditoria();
    }
    public String getBuscarCodigPlan(String Taller){
        String Plan="-1";
        try {
            String Str_Sql = "select IdPlan from JPlanAuditoria where IdTaller="+Taller;
            ResultSet xResult = this.JBase_Datos.SQL_QRY(this.Connection_BD,Str_Sql);
            if(xResult.next()){
                Plan = xResult.getString("IdPlan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," getBuscarCodigPlan() "+ e.getMessage());
        }
        return Plan;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe de Auditoria");
        setBounds(new java.awt.Rectangle(240, 90, 0, 0));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Chequeo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descripcion", "Si", "No"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane7.setViewportView(jTable1);

        jButton8.setText("Borrar Tabla");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8))
                    .addComponent(jScrollPane7))
                .addGap(27, 27, 27))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Metodologia Planeacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane8.setViewportView(jTextArea7);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCheckBox2.setText("Lista de Chequeo");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Codigo Plan Auditoria");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addGap(345, 345, 345)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(170, 170, 170))
        );

        jTabbedPane1.addTab("Planeacion", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Objetivo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Alcance");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Observaciones");

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alcance", jPanel5);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Area");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Proceso Examinado:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tipo de Informe");

        jButton7.setText("Guardar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane9.setViewportView(jTextArea8);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7)
                    .addComponent(jLabel10)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jButton7)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Encabezado", jPanel8);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Recomendaciones");

        jButton5.setText("Guardar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Recomendaciones", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Comentarios con persona (s)  Auditada (s)");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jButton6.setText("Guardar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cierre Auditoria", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Recomendaciones por Responsable de Autorizar");

        jButton1.setText("Autorizado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Autorizacion", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    // TODO add your handling code here:
    if (Estado){
        jPanel6.setVisible(false);
        Estado = false;
    }else{
        Estado = true;
        jPanel6.setVisible(true);
    }
}//GEN-LAST:event_jCheckBox2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        this.CrearPleancion();
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
    this.setInformeAuditoria();
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    this.setRecomendaciones();
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
    this.setCierre();
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
  if (isUserAut()){
        this.setAutorizacion();
  }
}//GEN-LAST:event_jButton1ActionPerformed
public boolean isUserAut(){
    boolean Control = false;
    try {
        String Str_Sql ="select * from JUser where Usuario='"+this.Usuario.toLowerCase()+"' and (idCargo=1 or idCargo=2)";
        ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,Str_Sql);
        if(xResult.next()){
            Control = true;
        }
        xResult.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this," isUserAut() "+ e.getMessage());
    }
    return Control;
}
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    JReportAudiSys rt = new JReportAudiSys(Integer.parseInt(this.IdentificadorPlanAuditoria));
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
    this.setEncabezado();
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
    ClearTable();
}//GEN-LAST:event_jButton8ActionPerformed
private void CargarAuditoria(){
    if (!getInformeAuditoria()){
        try{
            String StrSql ="";
            StrSql ="SELECT IdPlan, IdTaller, IdRiesgo, Ano, Mes, Dia, NombreAuditoria, AutorizadoPor, "+
                           "Objetivos, Alcances, Responsable1, Responsable2, TiempoEstimado, IdEstado "+
                           " FROM JPlanAuditoria WHERE IdPlan="+this.IdentificadorPlanAuditoria.trim();
            ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            while(xResult.next()){
                jTextArea1.setText(xResult.getString(9));
                jTextArea2.setText(xResult.getString(10));
                jLabel8.setText(xResult.getString(1));
            }
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,"CargarAuditoria() "+ e.getMessage());
        }
     }
     this.getChechkList();
     this.getPlaneacion();
}
private void getPlaneacion(){
    try{
            String StrSql ="SELECT IdPlan, ObservacionMetodologica "+
                           " FROM JPlaneacionAuditoria WHERE IdPlan="+this.IdentificadorPlanAuditoria.trim();
            ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            while(xResult.next()){
                jTextArea7.setText(xResult.getString(2));
            }
    }catch(Exception e ){
            JOptionPane.showMessageDialog(this,"getPlaneacion() "+ e.getMessage());
    }
}
private boolean getInformeAuditoria(){
    boolean Estado;
    Estado = false;
    try{
        String StrSql = "SELECT idPlan, Alcances, Objetivos, Observaciones, "+
                        "RecomendacionAuditor , RecomendacionCierre, RecomendacionAutorizacion, Descripcion, TipoInforme, Area "+
                        " FROM JInforme WHERE idPlan="+this.IdentificadorPlanAuditoria;
        ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
        if(xResult.next()){
            jLabel8.setText(xResult.getString(1));
            jTextArea2.setText(xResult.getString(2));
            jTextArea1.setText(xResult.getString(3));
            jTextArea3.setText(xResult.getString(4));
            jTextArea6.setText(xResult.getString(5));
            jTextArea5.setText(xResult.getString(6));
            jTextArea4.setText(xResult.getString(7));
            jTextArea8.setText(xResult.getString(8));
            String TipoInforme = xResult.getString(9);
            String Area = xResult.getString(10);
            this.busquedaArea(Area);
            this.busquedaTipoInforme(TipoInforme);
            Estado = true;
        }
    }catch(Exception e ){
        JOptionPane.showMessageDialog(this,"getInformeAuditoria() "+ e.getMessage());
    }
    return Estado;
}

public void CrearPleancion(){
    try{
        String StrSql = "SELECT * FROM JPlaneacionAuditoria WHERE IdPlan="+this.IdentificadorPlanAuditoria;
        ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
        if(xResult.next()){
            StrSql ="UPDATE  JPlaneacionAuditoria "+
                    "SET ObservacionMetodologica= '"+jTextArea7.getText().trim()+"'";
        }else{
            StrSql ="INSERT INTO JPlaneacionAuditoria (IdPlan, ObservacionMetodologica) "+
                    "VALUES ("+this.IdentificadorPlanAuditoria+" , '"+jTextArea7.getText().trim()+"' )";
        }
        boolean bResult =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
        if (bResult == true){
           JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");
        }else{
           JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente"); 
        } 
    }catch(Exception e ){
        JOptionPane.showMessageDialog(this,"CrearPleancion() "+ e.getMessage());
    }
    this.CrearCheckList();
}

public void CrearCheckList(){
    try{
        int CantidadFila = jTable1.getRowCount();
        int Fila = 0;
        String DecripcionActividad = "";
        try{ 
            DecripcionActividad = jTable1.getValueAt(Fila, 0).toString().trim(); 
           }catch(Exception e ){}
        String Si;
        String No;
        while ((Fila<= CantidadFila) && (!DecripcionActividad.equals(""))){
           Si = "";
           try{
             Si = jTable1.getValueAt(Fila, 1).toString().trim(); 
           }catch(Exception e){}
           No = "";
           try{
             No = jTable1.getValueAt(Fila, 2).toString().trim(); 
           }catch(Exception e ){}
           //AQUI DEBE CREARCE
           this.InsertCheckList(DecripcionActividad,Si,No, Fila);
           Fila++;
           DecripcionActividad = "";
           try{ 
            DecripcionActividad = jTable1.getValueAt(Fila, 0).toString().trim(); 
           }catch(Exception e ){}           
        }
    }catch(Exception e ){
        JOptionPane.showMessageDialog(this,"CrearCheckList() "+ e.getMessage());
    }
}
public void InsertCheckList(String DecripcionActividad, String Si, String No , int Consecutivo){
       String StrSql = "SELECT * FROM JCheckList WHERE IdPlan ="+this.IdentificadorPlanAuditoria+" AND IdCheck ="+Consecutivo;
       try{
               ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
               boolean Result;
               if(xResult.next()){
                   StrSql = "DELETE FROM JCheckList "
                            +" WHERE IdPlan ="+this.IdentificadorPlanAuditoria;
                   Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
               }
               StrSql = "INSERT INTO JCheckList (IdPlan,Descripcion,Si,No, IdCheck) "
                        +"VALUES ("+this.IdentificadorPlanAuditoria+", '"+DecripcionActividad.trim()+"','"+Si.trim()+"','"+No.trim()+"' , "+Consecutivo+")" ;
               Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
               if (Result){
                   JOptionPane.showMessageDialog(this,"Se ha Guardado Correctamente");
               }else{
                   JOptionPane.showMessageDialog(this,"No Se pudo Guardar Correctamente");
               }
        }catch(Exception e ){
               JOptionPane.showMessageDialog(this,"InsertCheckList() "+e.getMessage());
        }
}
public void getChechkList(){
    String StrSql = "SELECT t1.IdCheck , t1.Descripcion, t1.Si , t1.No FROM JCheckList as t1 WHERE IdPlan ="+this.IdentificadorPlanAuditoria+ 
                    " ORDER BY 1";
    Cabecera [0] = "Descripcion";
    Cabecera [1] = "Si";
    Cabecera [2] = "No";
    try{
            int FilaTabla = -1;
            ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            while(xResult.next()){
                FilaTabla++;
                Detalle [FilaTabla][0] = xResult.getString(2);
                Detalle [FilaTabla][1] = xResult.getString(3);
                Detalle [FilaTabla][2] = xResult.getString(4);
                jCheckBox2.setSelected(true);
                jPanel6.setVisible(true);
                Estado = true;
                jButton8.setEnabled(true);
            }
    }catch(Exception e ){
               JOptionPane.showMessageDialog(this,"getChechkList() "+e.getMessage());
    }
    jTable1.setModel(new javax.swing.table.DefaultTableModel(Detalle, Cabecera));
}
public boolean ExisteInforme(){
    String StrSql = "SELECT * FROM JInforme WHERE idPlan="+this.IdentificadorPlanAuditoria;
    boolean Estado = false;
    try{
        ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
        if(xResult.next()){
           Estado = true; 
        }
    }catch(Exception e ){
        JOptionPane.showMessageDialog(this,"ExisteInforme() "+ e.getMessage());
    }
    return Estado;
}
public void setInformeAuditoria(){
    String StrSql;
    boolean Result;
    try{
        if (!ExisteInforme()){
            StrSql  = "INSERT INTO JInforme  (idPlan,Objetivos,Alcances,Observaciones) "+
                      "VALUES ("+this.IdentificadorPlanAuditoria+", '"+jTextArea1.getText().trim()+"','"+jTextArea2.getText().trim()+"','"+jTextArea3.getText().trim()+"' )";
        }else{
            StrSql  = "UPDATE JInforme "+
                      "SET Alcances ='"+jTextArea2.getText().trim()+ "' " +
                      ",Objetivos    ='"+jTextArea1.getText().trim()+ "' " +
                      ",Observaciones  ='"+jTextArea3.getText().trim()+ "' " +
                      "WHERE idPlan = "+this.IdentificadorPlanAuditoria;
        }
        Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
        if (Result){
           JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");
        }else{
           JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente");
        }
        
    }catch(Exception  e){
        JOptionPane.showMessageDialog(this,"setInformeAuditoria() "+ e.getMessage());
    }
}

public void setRecomendaciones(){
    String StrSql;
    boolean Result;
    try{
        if (!ExisteInforme()){
          JOptionPane.showMessageDialog(this,"Debe estar Diligenciada y Guardada la ficha de Alcance");
        }else{
            StrSql  = "UPDATE JInforme "+
                      "SET RecomendacionAuditor   ='"+jTextArea6.getText().trim()+ "' " +
                      "WHERE idPlan = "+this.IdentificadorPlanAuditoria;
            Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
            if (Result){
                JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");
            }else{
                JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente");
            }
        }
    }catch(Exception  e){
        JOptionPane.showMessageDialog(this,"setRecomendaciones() "+ e.getMessage());
    }
}
public void setCierre(){
    String StrSql;
    boolean Result;
    try{
        if (!ExisteInforme()){
          JOptionPane.showMessageDialog(this,"Debe estar Diligenciada y Guardada la ficha de Alcance");
        }else{
            StrSql  = "UPDATE JInforme "+
                      "SET Alcances ='"+jTextArea1.getText().trim()+ "' " +
                      ",RecomendacionCierre   ='"+jTextArea5.getText().trim()+ "' " +
                      "WHERE idPlan = "+this.IdentificadorPlanAuditoria;
            Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
            if (Result){
                JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");
            }else{
                JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente");
            }
        }
    }catch(Exception  e){
        JOptionPane.showMessageDialog(this,"setCierre() "+ e.getMessage());
    }
}
public void setAutorizacion(){
    String StrSql;
    boolean Result;
    try{
        if (!ExisteInforme()){
          JOptionPane.showMessageDialog(this,"Debe estar Diligenciada y Guardada la ficha de Alcance");
        }else{
            StrSql  = "UPDATE JInforme "+
                      "SET Alcances ='"+jTextArea1.getText().trim()+ "' " +
                      ",RecomendacionAutorizacion   ='"+jTextArea4.getText().trim()+ "' " +
                      "WHERE idPlan = "+this.IdentificadorPlanAuditoria;
            System.out.println(""+StrSql);
            Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
            if (Result){
                JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");
            }else{
                JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente");
            }
            StrSql  = "UPDATE JPlanAuditoria "+
                      "SET IdEstado ='Finalizada'"+
                      " WHERE idPlan = "+this.IdentificadorPlanAuditoria;
            Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
            
        }
    }catch(Exception  e){
        JOptionPane.showMessageDialog(this,"setAutorizacion() "+ e.getMessage());
    }
}
private void getDivisiones(){
        try{
            String StrSql = "SELECT IdDependencia , Nombre "+
                            "FROM   JDependencia ";
            ResultSet  Result = JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            jComboBox1.removeAllItems();
            jComboBox1.addItem("");
            while (Result.next()){
              jComboBox1.addItem(Result.getString(2));
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog( this,"getDivisiones() "+e.getMessage());
        }
}
private void getTipoInforme(){
        try{
            String StrSql = "SELECT Id, Descripcion "+
                            "FROM   JTipoInformes ";
            ResultSet  Result = JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            jComboBox3.removeAllItems();
            jComboBox3.addItem("");
            while (Result.next()){
              jComboBox3.addItem(Result.getString(2));
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog( this,"getTipoInforme()"+e.getMessage());
        }
}
public void setEncabezado(){
    String StrSql;
    boolean Result;
    try{
        if (!ExisteInforme()){
          JOptionPane.showMessageDialog(this,"Debe estar Diligenciada y Guardada la ficha de Alcance");
        }else{
            StrSql  = "UPDATE JInforme "+
                      "SET Descripcion   ='"+jTextArea8.getText().trim()+ "' " +
                      ", TipoInforme   ='"+jComboBox3.getSelectedItem().toString().trim()+ "' " +
                      ", Area  ='"+jComboBox1.getSelectedItem().toString().trim()+ "' " +
                      "WHERE idPlan = "+this.IdentificadorPlanAuditoria;
            Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
            if (Result){
                JOptionPane.showMessageDialog(this,"Se Guardo Correctamente");
            }else{
                JOptionPane.showMessageDialog(this,"No se pudo Guardar Correctamente");
            }
        }
    }catch(Exception  e){
        JOptionPane.showMessageDialog(this,"setEncabezado(): "+ e.getMessage());
    }
}

private void busquedaTipoInforme(String Busqueda){
        for ( int i = 0 ; i < jComboBox3.getItemCount() ; i ++ ){
          if( jComboBox3.getItemAt(i).equals(Busqueda.trim())){
             jComboBox3.setSelectedIndex(i);
          }
        }
}
private void busquedaArea(String Busqueda){
        for ( int i = 0 ; i < jComboBox1.getItemCount() ; i ++ ){
          if( jComboBox1.getItemAt(i).equals(Busqueda.trim())){
             jComboBox1.setSelectedIndex(i);
          }
        }
}
private void ClearTable(){
    try{
        for(int i =0 ; i< 50; i ++){
                Detalle [i][0] = "";
                Detalle [i][1] = "";
                Detalle [i][2] = "";
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(Detalle, Cabecera));   
        String StrSql = "DELETE FROM JCheckList "
                            +" WHERE IdPlan ="+this.IdentificadorPlanAuditoria;
        boolean Result =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
        jCheckBox2.setSelected(false);
    }catch(Exception e ){
        JOptionPane.showMessageDialog(this," ClearTable() "+ e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeAuditoria(null,null,"",null, 0).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    // End of variables declaration//GEN-END:variables
}
