package Auditoria;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlanAuditoria.java
 *
 * Created on 1/03/2012, 11:47:37 AM
 */
/**
 *
 * @author GACA1186 (Garyn Jairo Carrillo Caballero-2012)
 */
import BD_Auditoria.JConeccion_AudiSys;
import Principal.*;
import java.sql.*;
import javax.swing.*;
import Auditoria.*;

public class PlanAuditoria extends javax.swing.JFrame {
    /** Creates new form PlanAuditoria */
    private JConeccion_AudiSys JBase_Datos;
    private Connection Connection_BD;
    
    private String PIdArea, PIdRiesgo;
    private int PIdTaller;
    private boolean EstadoBusqueda;
    private  ResultSet  Result;
    private Object [] Cabecera ;
    private Object [] [] Detalle  ;
    private int zaño, zmes, zdia;
    
    public PlanAuditoria(int IdTaller, String IdArea , String IdRiesgo) {
    
        this.PIdTaller = IdTaller;
        this.PIdArea = IdArea;
        this.PIdRiesgo = IdRiesgo;
        this.EstadoBusqueda = false;
        JBase_Datos = new JConeccion_AudiSys ();
     	Connection_BD = JBase_Datos.Open_BD();
        Cabecera =  new Object [3];
        Detalle  = new Object [50][3];
        initComponents();
        this.setAsignarTrabajo();
        this.setInformacion();
        jLabel9.setText("Taller No "+IdTaller);
        //if (this.EstadoBusqueda){
            this.setVisible(true);
        //}
        this.getInformacion();    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plan de Auditoria");
        setBounds(new java.awt.Rectangle(270, 160, 0, 0));
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Riesgo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Objeto de la Auditoria");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Recurso a Asignar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tiempo esperado (Hrs)");

        jButton1.setText("Asignar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Calificacion");

        jButton4.setText("Busqueda Avanzada..");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Fecha (aaa/mm/dd)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Taller No");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addGap(75, 75, 75)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addContainerGap()))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel9)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Asignacion de Recursos", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Causas del Riesgo");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdRiesgo", "IdCausa", "Descripcion Causa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Causa-Riesgo", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdCausa", "IdAccion", "Descripcion Accion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Acciones de la Causa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Acciones-Causas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
    try{
        if ((Result.next()) && (this.EstadoBusqueda == true)){
               String XNombreRiesgo = Result.getString(3);
               double Puntuacion = Double.valueOf(Result.getString(4));
               int IdTaller = Result.getInt(1);
               String IdRiesgo = Result.getString(2);
               jTextArea1.setText(XNombreRiesgo);
               jLabel10.setText(""+IdTaller);
               jLabel11.setText(IdRiesgo);
               this.setCausa(IdTaller, IdRiesgo);
               this.getInformacion(IdTaller,IdRiesgo);
       }
    }catch(Exception  e ){
        JOptionPane.showMessageDialog(this,"JButon Next "+e.getMessage());
    }
}//GEN-LAST:event_jButton3ActionPerformed
private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    if(!isError()){
        this.getFecha();
        this.setPlanAuditoria(this.PIdTaller , jLabel11.getText().trim(), zaño, zmes, zdia, jTextArea1.getText().trim(), jTextArea2.getText().trim(),
                            "" , jComboBox1.getSelectedItem().toString().trim() ,"",jTextField1.getText().trim());
        JMail Mail = new JMail(this.JBase_Datos, this.Connection_BD, jComboBox1.getSelectedItem().toString(),""+this.PIdTaller,jTextArea1.getText().trim(),jTextArea2.getText().trim(),jTextField1.getText().trim(), jTextField3.getText().trim());
        Mail.setVisible(true);
    }else{
        JOptionPane.showMessageDialog(this, "Debes diligenciar todos los campos para poder Asignar el Trabajo");
    }
}//GEN-LAST:event_jButton1ActionPerformed
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    try{
       if ( (Result.previous()) && (this.EstadoBusqueda == true)){
               String XNombreRiesgo = Result.getString(3);
               double Puntuacion = Double.valueOf(Result.getString(4));
               int IdTaller = Result.getInt(1);
               String IdRiesgo = Result.getString(2);
               jTextArea1.setText(XNombreRiesgo);
               jLabel10.setText(""+IdTaller);
               jLabel11.setText(IdRiesgo);
               this.setCausa(IdTaller, IdRiesgo);
               this.getInformacion(IdTaller,IdRiesgo);
       }
    }catch(Exception  e ){
        JOptionPane.showMessageDialog(this,"JButton Previuos "+e.getMessage());
    }
}//GEN-LAST:event_jButton2ActionPerformed
private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
    jButton3.setEnabled(false);
    jButton2.setEnabled(false);
}//GEN-LAST:event_jButton4ActionPerformed
private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField3ActionPerformed
private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
    // TODO add your handling code here:
    JFrame jf =new JFrame ("Calendario");
    MiCalendarioGestor cp = new MiCalendarioGestor();
    jf.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE);
    jf.add(cp);
    jf.setBounds(500, 500, 200, 200);
    jf.setResizable(false);
    jf.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    jf.setVisible(true);
    jTextField3.setText(cp.getAño()+"/"+cp.getMes()+"/"+cp.getDia());
}//GEN-LAST:event_jTextField3MouseClicked
    /*
            @param IdTaller,IdArea, IdRiesgo
 
     /*/

public void getInformacion(){
    try {
        String StrSql = "select Objetivos ,NombreAuditoria, Responsable1, TiempoEstimado, Ano, Mes, Dia from JPlanAuditoria where IDTaller = "+this.PIdTaller;
       ResultSet Rs = JBase_Datos.SQL_QRY(Connection_BD,StrSql);
        if(Rs.next()){
          jTextArea1.setText(Rs.getString("NombreAuditoria"));     
          jTextArea2.setText(Rs.getString("Objetivos"));
          jTextField1.setText(Rs.getString("TiempoEstimado"));
          jTextField3.setText(Rs.getString("Ano")+"/"+Rs.getString("Mes")+"/"+Rs.getString("Dia"));
          jComboBox1.setSelectedIndex(getBusquedaRespinsable(Rs.getString("Responsable1").trim()));
          jButton1.setEnabled(false);
          jButton2.setEnabled(false);
          jButton3.setEnabled(false);
          jButton4.setEnabled(false);
       }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Form: getInformacion()"+e.getMessage());
    }
}

    public int getBusquedaRespinsable(String Busqueda){
        int Pos = 0;
        int Cantidad = jComboBox1.getItemCount();
        
        for (int i = 0; i < Cantidad; i++) {
            if(jComboBox1.getItemAt(i).toString().equals(Busqueda)){
                Pos = i;
                i = Cantidad + 1;
            }
        }
        return Pos;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanAuditoria(0,"", "").setVisible(true);
            }
        });
    }
    private void setInformacion(){
        try{
            String XNombreRiesgo;    
            String IdRiesgo;
            String StrSql = "";
            double Puntuacion;
            int IdTaller;
            if(this.PIdTaller != 0){
                StrSql = "SELECT t1.IdTaller, t2.IDRiesgo , t2.Descripcion_Riesgo, t2.PuntuacionPlanAuditoria FROM JTaller as t1, JRiesgos as t2 "
                         +" WHERE t1.IdTaller = t2.IDTaller AND PlanAuditoria=true  AND  t2.IDTaller = "+this.PIdTaller;
            }
            if(!this.PIdArea.trim().isEmpty()){
                StrSql = "SELECT t1.IdTaller, t2.IDRiesgo , t2.Descripcion_Riesgo, t2.PuntuacionPlanAuditoria FROM JTaller as t1, JRiesgos as t2 ,  JDependencia t3"
                         +" WHERE t1.IdTaller = t2.IDTaller AND t1.IdDependencia = t3.IdDependencia "
                         +"AND PlanAuditoria=true  AND T3.Nombre ='"+this.PIdArea.trim()+"'";
            }       
            if(!this.PIdRiesgo.trim().isEmpty()){
                StrSql = "SELECT t1.IdTaller, t2.IDRiesgo , t2.Descripcion_Riesgo, t2.PuntuacionPlanAuditoria FROM JTaller as t1, JRiesgos as t2 "
                         +" WHERE t1.IdTaller = t2.IDTaller AND PlanAuditoria=true  AND t2.IDRiesgo = "+this.PIdRiesgo.trim();
            }
            
            Result = JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            if (Result.next()){
               this.EstadoBusqueda = true;
               XNombreRiesgo = Result.getString(3);
               IdRiesgo = Result.getString(2);
               IdTaller = Result.getInt(1);
               Puntuacion = Double.valueOf(Result.getString(4));
               jTextArea1.setText(XNombreRiesgo);
               jTextField2.setText(String.valueOf(Puntuacion));
               jLabel10.setText(""+IdTaller);
               jLabel11.setText(IdRiesgo);
               this.setCausa(IdTaller, IdRiesgo);
               this.getInformacion(IdTaller,IdRiesgo);
            }
            if (this.EstadoBusqueda == false){
                //JOptionPane.showMessageDialog(this,"No encontrado");
            }
            
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this, "Form: PlanAuditoria (setInformaion)"+e.getMessage());
        }
    }
    private void setCausa(int xTaller, String IdRiesgo){
         boolean Encontrado = false;
         String xCausa = "";
         try{
            String StrSql = "SELECT IDCausa, DescripcionCausa FROM JCausa as t1 "
                            +" WHERE t1.IdTaller ="+xTaller;
            ResultSet xResult = JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            int fila = -1;
            Cabecera [0] = "IdRiesgo";
            Cabecera [1] = "IdCausa";
            Cabecera [2] = "Descripcion Causa";
            
            while (xResult.next()){
                fila ++;
                Detalle [fila][0] = IdRiesgo;
                Detalle [fila][1] = xResult.getString(1);
                Detalle [fila][2] = xResult.getString(2);
                Encontrado = true;
                xCausa = String.valueOf( Detalle[fila][1]);
                
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this, "Form: PlanAuditoria (SetCausa)"+e.getMessage());
        }
         if (Encontrado){
            jTable1.setModel(new javax.swing.table.DefaultTableModel(Detalle, Cabecera));
            this.setAccion(xTaller);
         }
    }
    private void setAccion(int xIdTaller){
        boolean Encontrado = false;
        try{
            String StrSql = "SELECT t1.IdAccion, t1.Nombre , t2.IDCausas FROM JAcciones as t1 , JAccionCausas as t2 "
                            +" WHERE t1.IdTaller ="+xIdTaller+" AND t1.IdTaller=t2.IdTaller AND t1.IdAccion=t2.IdAccion ";
            ResultSet Resultx = JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            int fila = -1;
            Cabecera [0] = "IdCausa";
            Cabecera [1] = "IdAccion";
            Cabecera [2] = "Descripcion Accion";
            while (Resultx.next()){
                fila ++;
                Detalle [fila][0] = Resultx.getString(3);
                Detalle [fila][1] = Resultx.getString(1);
                Detalle [fila][2] = Resultx.getString(2);
                Encontrado = true;
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this, "Form: PlanAuditoria (SetAccion)"+e.getMessage());
        }
        if(Encontrado){
            jTable2.setModel(new javax.swing.table.DefaultTableModel(Detalle, Cabecera));
        }
    }
    private void setAsignarTrabajo(){
       try{
            String StrSql = "SELECT  t1.NombreCompleto,t1.PrimerNombre, t1.PrimerApellido,t1.SegundoApellido FROM  JUser as t1 , JCargos t2 "
                        +"WHERE t1.IdCargo = t2.IdCargo AND t1.Estado ='Activo' AND Nombre <> 'Jefe Auditoria' ";
            jComboBox1.removeAllItems();
            jComboBox1.addItem("");
            ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            while(xResult.next()){
                jComboBox1.addItem(xResult.getString("NombreCompleto") );
            }
       }catch(Exception e ){
           JOptionPane.showMessageDialog(this,"Form: PlanAuditoria (AsignarTrabajo)"+e.getMessage());
       }
    }
    private boolean isError(){
        boolean Validacion = false;
        if(jTextArea2.getText().trim().equals("")){
            Validacion = true;
        }
        if(jTextArea2.getText().trim().equals("")){
            Validacion = true;
        }
        if(jTextField1.getText().trim().equals("")){
            Validacion = true;
        }
        if(jTextField2.getText().trim().equals("")){
            Validacion = true;
        }
        if(jTextField3.getText().trim().equals("")){
            Validacion = true;
        }
        if(jComboBox1.getSelectedItem().toString().trim().isEmpty()){
            Validacion = true;
        }
        return Validacion;
    }
    private void setPlanAuditoria(int IdTaller , String IdRiesgo, int xaño, int xmes, int xdia, String NombreAuditoria, String xObjetivos,
        String xAlcance, String xResponsable1, String xResponsable2,String xTiempo){
        try{
            String StrSql = "SELECT IdTaller , IdRiesgo "+
                            "FROM JPlanAuditoria "+
                            "WHERE IdTaller="+IdTaller+" AND IdRiesgo ='"+IdRiesgo+"'";
            ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);
            boolean Inser = false;
            if(!xResult.next()){ 
                StrSql = "INSERT INTO JPlanAuditoria "+
                         "(IdTaller,IdRiesgo,Ano,Mes,Dia,NombreAuditoria,Objetivos,Alcances,Responsable1,Responsable2,TiempoEstimado,IdEstado) " +
                         "VALUES "+
                         "("+IdTaller+",'"+IdRiesgo.trim()+"',"+xaño+","+xmes+","+xdia+",'"+NombreAuditoria.trim()+
                         "','"+xObjetivos.trim()+"','"+xAlcance.trim()+"','"+xResponsable1.trim()+"','"+xResponsable2.trim()+"','"+xTiempo.trim()+"' , 'Asignada') ";
                Inser = true;
            }else{
                StrSql = "UPDATE JPlanAuditoria "+
                         "SET Ano ="+xaño+
                         " ,Mes ="+xmes+
                         " ,Dia ="+xdia+
                         " ,NombreAuditoria ='"+NombreAuditoria.trim()+"'"+
                         " ,Objetivos ='"+xObjetivos.trim()+"'"+
                         " ,Alcances ='"+xAlcance.trim()+"'"+
                         " ,Responsable1 ='"+xResponsable1.trim()+"'"+
                         " ,Responsable2 ='"+xResponsable2.trim()+"'"+
                         " ,TiempoEstimado ='"+xTiempo.trim()+"'"+
                         " WHERE IdTaller ="+IdTaller+" AND IdRiesgo ='"+IdRiesgo+"'";
            }
            System.out.println(""+StrSql);
            boolean Exec =  JBase_Datos.Exc_Sql(Connection_BD,StrSql);
            JOptionPane.showMessageDialog(this, "Se realizo la Asignacion de forma Correcta");
            if(Exec){
                if (Inser){
                    JOptionPane.showMessageDialog(this,"Asignado Correctamente");
                }else{
                    JOptionPane.showMessageDialog(this,"Actualizado Correctamente");
                }
            }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(this,"Form: PlanAuditoria (SetPlanAuditoria)"+e.getMessage());
        }
    }
    private void getFecha(){
        int Tamaño = jTextField3.getText().trim().length();
        String Concatena = "";
        int Cuenta = 0, i;
        for( i =0 ; i< Tamaño ; i++){
            if(jTextField3.getText().charAt(i)!='/') {
                if (Cuenta == 1 ){
                    zaño =  Integer.parseInt(Concatena);
                    Concatena  = "";
                }
                if (Cuenta == 2 ){
                    zmes =  Integer.parseInt(Concatena);
                    Concatena  = "0";
                    Cuenta ++;
                }
                Concatena= Concatena +jTextField3.getText().charAt(i);
            }else{
                Cuenta ++;
            }
        }
        zdia =  Integer.parseInt(Concatena);
    }
    private void getInformacion(int IdTaller , String IdRiesgo){
            try{
                String StrSql = "SELECT IdTaller,IdRiesgo,Ano,Mes,Dia,NombreAuditoria,Objetivos,Responsable1,TiempoEstimado "+
                            "FROM JPlanAuditoria "+
                            "WHERE IdTaller="+IdTaller+" AND IdRiesgo ='"+IdRiesgo+"'";
                ResultSet xResult =  JBase_Datos.SQL_QRY(Connection_BD,StrSql);  
                if(xResult.next()){
                    jTextField3.setText(""+xResult.getString(3)+"/"+xResult.getString(4)+"/"+xResult.getString(5)); 
                    jTextArea2.setText(xResult.getString(7));
                    jTextField1.setText(xResult.getString(9));
                    busquedeResponsable(xResult.getString(8));
                }else{
                    jTextField3.setText(""); 
                    jTextArea2.setText("");
                    jTextField1.setText("");
                    jComboBox1.setSelectedIndex(0);
                }
            }catch(Exception e ){
               JOptionPane.showMessageDialog(this,"Form: PlanAuditoria (getInformacion)"+e.getMessage());
            }
    }
    private void busquedeResponsable(String Busqueda){
        for ( int i = 0 ; i < jComboBox1.getItemCount() ; i ++ ){
          if( jComboBox1.getItemAt(i).equals(Busqueda.trim())){
             jComboBox1.setSelectedIndex(i);
          }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
