package Subsidio;


import Subsidio.*;
import Subsidio.JEmpleados;
import BD_As400.JConection;
import Subsidio.Escolar.JAuxEscolar;
import Subsidio.Universitarios.JHijosMayores;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Garyn Carrillo
 */
public class JBusquedaEmpleados extends javax.swing.JFrame {

    private JConection JBase_Datos;
    private Connection Cn; 
    private JEmpleados Afiliado;
    
    private Object [] Cabecera ;
    private Object [] [] Detalle  ;
    private int fila ;
    private String Usuario;
    /**
     * Creates new form JBusquedaEmpleados
     */
    
    public JBusquedaEmpleados(JConection JBase_Datos3, Connection Cn2, String Usuario) {
        this.Usuario = Usuario;
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        Cabecera =  new Object [5];
        Detalle  = new Object [1000][5];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Empleado");
        setBounds(new java.awt.Rectangle(150, 20, 0, 0));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "Recibe Subsidio", "Empresa", "Fecha Afiliacion"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Documento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)))
                        .addGap(0, 228, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void getTrabajadorActivo(){
        this.BorrarTabla();
        if (!jTextField1.getText().trim().equals("")) {
            try {
                int Documento =Integer.parseInt(jTextField1.getText().trim());
                Afiliado = new JEmpleados(Documento,this.JBase_Datos,this.Cn);
                this.setDetalleTabla();
            }catch(Exception e ){
                JOptionPane.showMessageDialog(null,"Class: JBusquedaEmpleados getTrabajadorActivo() " +e.getMessage());
            }
        }else{
            if (!jTextField2.getText().trim().equals("")){
                this.getInformacionEmpleadoNombre();
            }
        }
        
    }
    public void setDetalleTabla(){
        this.Cabecera [0] ="Documento";
        this.Cabecera [1] ="Nombre";
        this.Cabecera [2] ="Recibe Subsidio";
        this.Cabecera [3] ="Empresa";
        this.Cabecera [4] ="Fecha Afiliacion";
        if (this.Afiliado.getEstado()){
            fila = fila + 1;
            this.Detalle[0][0] = ""+this.Afiliado.getDocumento();
            this.Detalle[0][1] = ""+this.Afiliado.getNombre();
            this.Detalle[0][2] = ""+this.Afiliado.getRecibeSubsidio();
            this.Detalle[0][3] = ""+this.Afiliado.getEmpresa().getCodigo();
            this.Detalle[0][4] = ""+this.Afiliado.getFechaAfiliacion();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(Detalle, Cabecera));

    }
     public void getInformacionEmpleadoNombre(){
             boolean SwControl = false;
             try {
                 String StrSql = "SELECT  TRADOC,TRANOM, TRAFAC, TRASRS,EMPCOD   FROM SUBSILIB.MTRABAJ WHERE tranom like '%"+jTextField2.getText().trim().toUpperCase()+"%'";
                 ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,StrSql);
                 fila = -1;
                 this.Cabecera [0] ="Documento";
                 this.Cabecera [1] ="Nombre";
                 this.Cabecera [2] ="Recibe Subsidio";
                 this.Cabecera [3] ="Empresa";
                 this.Cabecera [4] ="Fecha Afiliacion";
                 while(rs.next()) {
                     fila++;
                     this.Detalle[fila][0] = rs.getInt("TRADOC");
                     this.Detalle[fila][1] = rs.getString("TRANOM");
                     if (rs.getInt("TRASRS")==1) {
                         this.Detalle[fila][2] = "true";
                     }else{
                         this.Detalle[fila][2] = "false";
                     }
                     this.Detalle[fila][3] = rs.getString("EMPCOD");
                     this.Detalle[fila][4] = rs.getInt("TRAFAC");
                }
                 //System.out.println("CORRECTO2");
                 jTable1.setModel(new javax.swing.table.DefaultTableModel(Detalle, Cabecera));
                 //System.out.println("CORRECTO2");
            }catch(Exception e ){
                JOptionPane.showMessageDialog(null,"Class: JBusquedaEmpleados getInformacionEmpleadoNombre() " +e.getMessage());
            } 
             
    }
    
public void BorrarTabla(){
    for (int i = 0; i < Cabecera.length; i++) {
        this.Detalle[i][0]="";
        this.Detalle[i][1]="";
        this.Detalle[i][2]="";
        this.Detalle[i][3]="";
        this.Detalle[i][4]="";
    }
    fila = -1;
}    
 
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 0)!=null){
            try{
                 System.out.println("Buscar ventana ");
                int XDocumento = Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                System.out.println("CLICK "+XDocumento);
                JFamilia fm = new JFamilia(XDocumento, this.JBase_Datos, this.Cn, this.Usuario);
                fm.setVisible(true);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Class: JBusquedaEmpleados_Click() " +e.getMessage());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.getTrabajadorActivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            this.getTrabajadorActivo();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            this.getTrabajadorActivo();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JBusquedaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JBusquedaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JBusquedaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JBusquedaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JBusquedaEmpleados(null, null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
