/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Subsidio.Aportes;

import BD_As400.JConection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;

/**
 *
 * @author GACA1186
 */
public class JLiquidador extends javax.swing.JFrame {

    /**
     * Creates new form JLiquidador
     */
    
    private Vector CabOportuno;
    private Vector FilaOportuno;
    private Vector DetOportuno;
    
    private Vector EmpresaXCantidad;
    private Vector CantidadXEmpresa;
    private JConection JBase_Datos;
    private Connection Cn;
    private SimpleDateFormat formato;
    private Vector Cab, Det, Fila;
    private Vector Ano_Mes ;
    private Vector V_interes ;
    private Vector V_Dias_Periodo ;
    private String NumeroFormato = "###,###,###,###.##";
    private DecimalFormat JFormato ;
    private Vector PFila;
    private Vector PCab;
    
    public JLiquidador(JConection JBase_Datos3, Connection Cn2) {
        PCab = new Vector();
        PCab.add("Periodo");
        PCab.add("Interes");
        PCab.add("No Dias");
        PFila = new Vector();
        Ano_Mes = new Vector();
        V_interes = new Vector();
        V_Dias_Periodo = new Vector();
        
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        formato = new SimpleDateFormat("yyyyMMdd");
        Cab = new Vector();
        Cab.add("Nro Dia");
        Cab.add("% Interes");
        Cab.add("valor ");
        Fila = new Vector();
        JFormato= new DecimalFormat(NumeroFormato);
        
        
        CabOportuno= new Vector();
        CabOportuno.add("Codigo");
        CabOportuno.add("Fecha Norma");
        CabOportuno.add("Fecha Pago");
        CabOportuno.add("Tipo");
        CabOportuno.add("Cantidad");
        FilaOportuno = new Vector();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liquidador de Aportes e Intereses");

        jTextField2.setEditable(false);
        jTextField2.setEnabled(false);

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Dia", "% Interes", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nit");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fecha de Pago");

        jTextField4.setEditable(false);
        jTextField4.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Digitos");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Independiente", "Empleador Menos 200", "Empleador con 200 o Mas", " " }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tipo Empleador");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Periodo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fecha Fin");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Vlr Nomina");

        jTextField7.setEnabled(false);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Periodo", "Interes", "No Dias"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel3)))
                                .addGap(0, 745, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                                        .addComponent(jButton1)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel4)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel7))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(4, 4, 4)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulador", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nit", "Razon Social", "Periodo", "Valor"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("Ejecutar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jButton2)
                        .addContainerGap(601, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(30, 30, 30))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Saltos", jPanel2);

        jButton4.setText("Analisis");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha Norma", "Fecha de Pago", "Tipo", "Cantidad"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pago oportuno", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Date StringToDate(String SFecha, String Formato){
        try {
            SimpleDateFormat sdf = new SimpleDateFormat(Formato);
            Date fecha = sdf.parse(SFecha);
            
            return fecha;
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return null;
    }
    
    public Date  sumaDias(Date Fecha, int dias){
        Calendar cal = Calendar.getInstance();
        cal.setTime(Fecha);
        cal.add(Calendar.DAY_OF_YEAR, dias);
        return cal.getTime();
    }
    
    public int  getDiasSemana(Date date){
        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(date);
        return cal.get(Calendar.DAY_OF_WEEK);
    }
    
    public int getCalendario_Aporte(String DDigitos, int TipoEmpleador){
        int Dias = -1;
        try {
            String Str_Sql="";
            int Digito=Integer.parseInt(DDigitos);
            if(TipoEmpleador == 1){
                Str_Sql =" select NRO_DIA from selinlib.JLAPORTES where IND_INI<="+Digito+" and IND_FIN>="+Digito;
            }
            if(TipoEmpleador == 2){
                Str_Sql =" select * from  selinlib.JLAPORTES where EMN2_INI<="+Digito+" and EMN2_FIN>="+Digito;
            }
            if(TipoEmpleador == 3){
                Str_Sql =" select * from  selinlib.JLAPORTES where EMY2_INI<="+Digito+" and EMY2_FIN>="+Digito;
            }
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(rs.next()){
                Dias=rs.getInt("NRO_DIA");
            }
            rs.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return  Dias;
    }
    
    public Date getUltimoDia(String AnoMesDia){
        try {
          Calendar cal = Calendar.getInstance();
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
          Date Fecha = sdf.parse(AnoMesDia);
          cal.setTime(Fecha);
          cal.add(Calendar.MONTH, 1);
          Fecha = cal.getTime();
          cal.add(Calendar.DAY_OF_WEEK, -1);        
          return cal.getTime();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
        return null;
    }
    public double getPorcentaje_Interes(String Ano   , String Mes){
        double Porcentaje = 0;
        try {
            String Str_Sql ="select * from selinlib.JLINTERES where Ano="+Ano+" and Mes="+Mes;
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(rs.next()){
                Porcentaje =rs.getDouble("porc");
            }
            rs.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage());
        }
        return Porcentaje;
    }
    
    public double[] getPorcentaje_Cantidad(String PAno_Mes){
            int pos = 0;
            double Porcentaje_Cantidad[]= new double [2];
            
            while(pos<Ano_Mes.size()){
                if (Ano_Mes.elementAt(pos).toString().equals(PAno_Mes)){
                    Porcentaje_Cantidad[0]=Double.parseDouble(""+V_interes.elementAt(pos));
                    Porcentaje_Cantidad[1]=Double.parseDouble(""+V_Dias_Periodo.elementAt(pos));
                    pos = pos +Ano_Mes.size();
                }
                pos++;
            }
            return  Porcentaje_Cantidad;
                    
    }
    
    public void geTabla_Resumen(){
            int pos = 0;
            PFila.clear();
            while(pos<Ano_Mes.size()){
                    Vector PDet = new Vector();
                    PDet.add(""+Ano_Mes.elementAt(pos));
                    PDet.add(""+V_interes.elementAt(pos));
                    PDet.add(""+V_Dias_Periodo.elementAt(pos));
                    PFila.add(PDet);
                    pos++;
                    
            }
            jTable3.setModel(new javax.swing.table.DefaultTableModel(PFila, PCab));
                    
    }

    public void Simulacion(Date FechaInicial , Date FechaFinal, String Ano ,String Mes, double VlrNomina){
        try {
            
            int FIncial = Integer.parseInt(""+formato.format(FechaInicial));
            int FFinal = Integer.parseInt(""+formato.format(FechaFinal));
            int FActual = FIncial;
            Date TActual = FechaInicial;
            Fila.clear();
            boolean Sw=true;
            double cuentaDias = 0;
            Ano_Mes.clear();
            V_interes.clear();
            V_Dias_Periodo.clear();
            String Fecha_Posterior=String.valueOf(FActual).substring(0, 6);
            String XAno="";
            String XMes ="";
            int Cuenta_dias_Periodo =0;
            while(FActual<=FFinal){
                Date Tmp = sumaDias(TActual, 1);
                String Sfecha = ""+formato.format(Tmp);
                XAno =Sfecha.substring(0, 4);
                XMes = Sfecha.substring(4, 6);
                String XFecha = XAno+XMes;
                Cuenta_dias_Periodo++;
                if(!Fecha_Posterior.equals(XFecha)){
                        Ano_Mes.add(""+Fecha_Posterior);
                        V_interes.add(getPorcentaje_Interes(XAno,Fecha_Posterior.substring(4, 6)));
                        V_Dias_Periodo.add(Cuenta_dias_Periodo);
                        Fecha_Posterior = XFecha;
                        Cuenta_dias_Periodo=0;
                }
    
                FActual = Integer.parseInt(""+formato.format(Tmp));
                TActual =Tmp;
                cuentaDias++;
              
            }
            if(Cuenta_dias_Periodo!=0){
                 Ano_Mes.add(""+Fecha_Posterior);
                 V_interes.add(getPorcentaje_Interes(XAno,XMes));
                 V_Dias_Periodo.add(Cuenta_dias_Periodo);
            }

            //Tablas de interes();
            geTabla_Resumen();            
            FIncial = Integer.parseInt(""+formato.format(FechaInicial));
            FFinal = Integer.parseInt(""+formato.format(FechaFinal));
            FActual = FIncial;
            TActual = FechaInicial;
            Fila.clear();
            Sw=true;
            cuentaDias = 0;
            double Total =0;
            
            double Porcentaje_Cantidad [];
            while(FActual<FFinal){
                Date Tmp = sumaDias(TActual, 1);
                FActual = Integer.parseInt(""+formato.format(Tmp));
                Det = new Vector();
                Det.add(""+FActual);
                Porcentaje_Cantidad  = getPorcentaje_Cantidad(String.valueOf(FActual).substring(0, 6));
                //System.out.println("Fecha "+String.valueOf(FActual)+" Porcentaje "+Porcentaje_Cantidad[0]+" Cantidad  "+Porcentaje_Cantidad[1]);
                double porcentaje2= (1+Porcentaje_Cantidad[0]);
                double potencia = (Porcentaje_Cantidad[1]/366);
                double Interes =   (Math.pow(porcentaje2  ,potencia ));
                Interes = Interes -1;
            
                
                Det.add(""+Interes);
                Total =Total+(Interes* VlrNomina);
                Det.add(""+JFormato.format(Interes* VlrNomina));
                Fila.add(Det);
                TActual =Tmp;
                cuentaDias++;
            }
            if(Total!= 0){
                Det = new Vector();
                Det.add("Total ");
                Det.add("--->>> ");
                Det.add(""+JFormato.format(Total));
                Fila.add(Det);
            }
            
            jTable1.setModel(new javax.swing.table.DefaultTableModel(Fila, Cab));
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage());
        }
    }
    
    
    
    
    
    
    public Date getBuscarDiasHabiles(int PDias){
        try {
            String FNueva=jTextField5.getText().trim();
            String  Ano = FNueva.substring(0, 4);
            String  Mes = FNueva.substring(4, 6);
            FNueva = Ano+"/"+Mes+"/01";
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            Date fecha = sdf.parse(FNueva);
             int Contar = 0;
             while(Contar<=PDias){
                            int CDia = getDiasSemana(fecha);
                            if(CDia==1){
                                //Domingo
                                fecha = sumaDias(fecha,1);
                            }else{                    
                                if(CDia==7){
                                    //Sabado
                                    fecha = sumaDias(fecha,2);
                                }else{
                                    //Otro dia revisa si es festivo
                                    FNueva = formato.format(fecha);
                                    boolean Festivo = this.isFestivo(FNueva);
                                    if(Festivo){
                                        fecha = sumaDias(fecha,1);
                                    }else{
                                         Contar++; 
                                         if(Contar<PDias){ 
                                            fecha = sumaDias(fecha,1);
                                         }
                                    }
                                }
                            }
                            
                    }
             return fecha;
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "  "+e.getMessage()); 
        }
        return null;
    }
    
    
    
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (this.jTextField1.getText().trim().equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar el NIT");
        }else{
            String Nit =  this.jTextField1.getText().trim();
            int Cantidad = Nit.length();
            String Digitos =Nit.substring(Cantidad-2, Cantidad);
            jTextField4.setText(Digitos);
            String FNueva =" ";
            String Ano ="";
            String Mes ="";
            if(jComboBox6.getSelectedIndex()!=0){
                
                int PDias = getCalendario_Aporte(Digitos, jComboBox6.getSelectedIndex());
                // Aqui es donde debe buscar los dias habiles
                jTextField7.setText(""+PDias);
                Date fecha = getBuscarDiasHabiles_2(PDias, jTextField5.getText().trim());
                
                
                FNueva=jTextField5.getText().trim();
                Ano = FNueva.substring(0, 4);
                Mes = FNueva.substring(4, 6);
                if(PDias<10){
                    FNueva = Ano+"/"+Mes+"/0"+PDias;
                }else{
                    FNueva = Ano+"/"+Mes+"/"+PDias;
                }
                Date FechaFinal = getUltimoDia(Ano+"/"+Mes+"/01");
      
                
                try{
           
                    
                    jTextField2.setText(formato.format(fecha));
                    
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                    String PAno = jTextField3.getText().trim().substring(0, 4);
                    String PMes = jTextField3.getText().trim().substring(4, 6);
                    String PDia = jTextField3.getText().trim().substring(6, 8);
                    String TFechaFin =PAno+"/"+PMes+"/"+PDia;
                    FechaFinal = sdf.parse(TFechaFin);
                    Simulacion(fecha, FechaFinal, Ano, Mes,Double.parseDouble(jTextField6.getText().trim()));
                    
                }catch(Exception e){
                    javax.swing.JOptionPane.showMessageDialog(this, "  "+e.getMessage()); 
                }
            }else{
               javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el Tipo de Empleador"); 
            }
            
            
        }
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
public Date getBuscarDiasHabiles_2(String Fecha, int PDias){
        try {
            String FNueva=Fecha;
            String  Ano = FNueva.substring(0, 4);
            String  Mes = FNueva.substring(4, 6);
            String Dia =FNueva.substring(6, 8);
            FNueva = Ano+"/"+Mes+"/"+Dia;
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            Date fecha = sdf.parse(FNueva);
             int Contar = 0;
             while(Contar<=PDias){
                            int CDia = getDiasSemana(fecha);
                            if(CDia==1){
                                //Domingo
                                fecha = sumaDias(fecha,1);
                            }else{                    
                                if(CDia==7){
                                    //Sabado
                                    fecha = sumaDias(fecha,2);
                                }else{
                                    //Otro dia revisa si es festivo
                                    FNueva = formato.format(fecha);
                                    boolean Festivo = this.isFestivo(FNueva);
                                    if(Festivo){
                                        fecha = sumaDias(fecha,1);
                                    }else{
                                         Contar++; 
                                         if(Contar<PDias){ 
                                            fecha = sumaDias(fecha,1);
                                         }
                                    }
                                }
                            }
                            
                    }
             return fecha;
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "  "+e.getMessage()); 
        }
        return null;
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Fecha = javax.swing.JOptionPane.showInputDialog("aaaa/mm/dd");
        javax.swing.JOptionPane.showMessageDialog(this,""+getBuscarDiasHabiles_2(Fecha,60));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        llenar_Vector();
        Analisis_Empresa();
        
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public int Buscar_EmpresaXCantidad(String PCodigo){
        String C ="0";
        try {
             for (int i = 0; i < EmpresaXCantidad.size(); i++) {
                if (EmpresaXCantidad.elementAt(i).toString().equals(PCodigo)){
                   C = CantidadXEmpresa.elementAt(i).toString();
                }
           }
        
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this," Buscar_EmpresaXCantidad "+e.getMessage());
        }
        return Integer.parseInt(C);
    }
            
    
    public void llenar_Vector(){
            try {
                
               String SQL = "Delete from selinlib.JEMPCANTID ";  
               boolean result = JBase_Datos.Exc_Sql(this.Cn,SQL);
               
               SQL = "Delete from selinlib.JEMPBLOQUE ";  
               result = JBase_Datos.Exc_Sql(this.Cn,SQL);        
                       
               SQL = "insert into  selinlib.JEMPCANTID (codigo,cantidad) select empcod , count(*) as cantidad from subsilib.mtrabaj "+
                         " group by empcod ";  
               
               result = JBase_Datos.Exc_Sql(this.Cn,SQL);
                
               EmpresaXCantidad = new Vector();
               CantidadXEmpresa = new Vector();
               SQL = "Select * from selinlib.JEMPCANTID ";
               ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,SQL);
               while(rs.next()){
                   EmpresaXCantidad.add(rs.getInt("codigo"));
                   CantidadXEmpresa.add(rs.getInt("cantidad"));
               }
               rs.close();
               
            } catch (Exception e) { 
                javax.swing.JOptionPane.showMessageDialog(this," llenar_Vector() "+e.getMessage());
            }
    }
            
    public void Analisis_Empresa(){
        try {
            String Str_Sql = "select EMPPRI, EMPTAF, EMPCOD , EMPNIT from subsilib.MEMPVAL ";
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            String FNueva=javax.swing.JOptionPane.showInputDialog("Ingrese el AAAAMM");
            
            //LLenar vector con informacion
            while(rs.next()){
                int Codigo = rs.getInt("EMPCOD");
                String Nit = rs.getString("EMPNIT");
                int empri = rs.getInt("EMPPRI");
                int emtaf  = rs.getInt("EMPTAF");
                Analisis_2(Codigo ,Nit ,empri  , emtaf , FNueva);
            }
            rs.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this," Analisis_Empresa() "+e.getMessage());
        }
    }
            
    
    public void Analisis_2(int PCodigo ,String PNit, int PEmpri, int PEmptaf, String FNueva){
        try{
            // TODO add your handling code here:
            int Cant = -1;
            String Nit =  ""+PNit;
            int Cantidad = Nit.length();
            String Digitos =Nit.substring(Cantidad-2, Cantidad);
            
            String Ano ="";
            String Mes ="";
            int Tipo = 0;
            if ((PEmpri == 5) && (PEmptaf==1)){
               //Independientes
               Tipo = 1;      
            }else{
                    //Empresas
                    String Txt = String.valueOf(PCodigo);
                    Cant = Buscar_EmpresaXCantidad(Txt);
                    if(Cant<200){
                        Tipo = 2;
                    }else{
                        Tipo = 3;
                    }
                    
            }
            int PDias = getCalendario_Aporte(Digitos, Tipo);
            //////////////////////////////////////////////////////////////////////////////////////////
            Date fecha = getBuscarDiasHabiles_2(PDias, FNueva);
            //Periodo de Analisis
            Ano = FNueva.substring(0, 4);
            Mes = FNueva.substring(4, 6);
            if(PDias<10){
                  FNueva = Ano+"/"+Mes+"/0"+PDias;
            }else{
                  FNueva = Ano+"/"+Mes+"/"+PDias;
            }
                 Date FechaFinal = getUltimoDia(Ano+"/"+Mes+"/01");
                 SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                 String PAno = Ano ;
                 String PMes =  Mes;
                 String PDia = "31";
                 String TFechaFin =PAno+"/"+PMes+"/"+PDia;
                 FechaFinal = sdf.parse(TFechaFin);
                 String SQL="insert into selinlib.JEMPBLOQUE (CODIGO, NIT,FECNORMA, FECPAGO,TIPO,EMPLEADO) VALUES ("+PCodigo+","+PNit+","+
                         formato.format(fecha)+","+PEmptaf+","+Tipo+","+Cant+")";
                 //System.out.println(""+SQL);
                 boolean result = JBase_Datos.Exc_Sql(this.Cn,SQL);
                 
                 DetOportuno = new Vector();
                 DetOportuno.add(""+PCodigo);
                 DetOportuno.add(""+formato.format(fecha));
                 DetOportuno.add(""+PEmptaf);
                 DetOportuno.add(""+Tipo);
                 DetOportuno.add(""+Cant);
                 FilaOportuno.add(DetOportuno);
                 jTable4.setModel(new javax.swing.table.DefaultTableModel(FilaOportuno, CabOportuno));
                   
        }catch(Exception e){
                  javax.swing.JOptionPane.showMessageDialog(this, " Analisis_2  "+e.getMessage()); 
        }
            
    }
          
    
    public Date getBuscarDiasHabiles_2(int PDias, String FECHA){
        try {
            String FNueva=FECHA;
            String  Ano = FNueva.substring(0, 4);
            String  Mes = FNueva.substring(4, 6);
            FNueva = Ano+"/"+Mes+"/01";
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            Date fecha = sdf.parse(FNueva);
             int Contar = 0;
             while(Contar<=PDias){
                            int CDia = getDiasSemana(fecha);
                            if(CDia==1){
                                //Domingo
                                fecha = sumaDias(fecha,1);
                            }else{                    
                                if(CDia==7){
                                    //Sabado
                                    fecha = sumaDias(fecha,2);
                                }else{
                                    //Otro dia revisa si es festivo
                                    FNueva = formato.format(fecha);
                                    boolean Festivo = this.isFestivo(FNueva);
                                    if(Festivo){
                                        fecha = sumaDias(fecha,1);
                                    }else{
                                         Contar++; 
                                         if(Contar<PDias){ 
                                            fecha = sumaDias(fecha,1);
                                         }
                                    }
                                }
                            }
                            
                    }
             return fecha;
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "  "+e.getMessage()); 
        }
        return null;
    }
    
    
    
    
    
    
    public boolean isFestivo(String Fecha){
        boolean Festivo = false;
        try {
            String Str_Sql =" select * from  adamco.tdnla where DNLFEC ="+Fecha;
            ResultSet rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(rs.next()){
                Festivo = true;
            }
            rs.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, " "+e.getMessage()); 
        }
        return Festivo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Date Fecha;
        Date Fecha2;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLiquidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLiquidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLiquidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLiquidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new JLiquidador(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
