/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fondo_Ley_NIFF_2020;

import Fondo_ley_NIIF.*;
import FondosLey.*;
import BD_As400.JConection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author GACA1186
 */
public class JConcialiaBancos extends javax.swing.JFrame {

    /**
     * Creates new form JConcialiaBancos
     */
     private String Ctamov2, Debmov2,Credmov2,Termov2;
     private Vector Cabecera;
     private Vector Fila;
     private Vector Detalle;
     private SimpleDateFormat d;
     private String NumeroFormato = "##############";
     private DecimalFormat JFormato ;
     private  String jTFechaIncial;
     private  String jTFechaFinal;
     private JConection JBase_Datos;
     private Connection Cn;
    public JConcialiaBancos(JConection JBase_Datos3, Connection Cn2, String Usuariox) {
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        Cabecera = new Vector();
        Fila = new Vector();
        JFormato= new DecimalFormat(NumeroFormato);
        
        initComponents();
        this.setCabecera();
        d = new SimpleDateFormat("yyyyMMdd");
        jXDatePicker4.setFormats("yyyyMMdd");
        jXDatePicker6.setFormats("yyyyMMdd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker5 = new org.jdesktop.swingx.JXDatePicker();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jXDatePicker4 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker6 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cuenta", "Descripcion", "Debito", "Credito", "Fecha", "Documento Fuente", "Numero Documento", "Cuenta 2", "Debito", "Creditó"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Ver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jXDatePicker6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap(415, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jXDatePicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jXDatePicker6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conciliar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   
        jTFechaIncial = d.format(jXDatePicker4.getDate()).toString();
        jTFechaFinal = d.format(jXDatePicker6.getDate()).toString();
        this.setBancos();
        this.setTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
             String PFecha = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
             String PNumDoc = jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString();
             String PCuenta = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
             JDetalleContable Frm_JDetalleContable =  new JDetalleContable(this.JBase_Datos, this.Cn, PFecha, PNumDoc, PCuenta);
             Frm_JDetalleContable.setVisible(true);       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," Frm_Detalle()  "+e.getMessage()); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    
    
    public void setBancos(){
        try {
            String Str_Sql =" Delete from  selinlib.JFCONCIBAN Where fecmov >="+this.jTFechaIncial.trim()+" and fecmov<= "+jTFechaFinal.trim();
            boolean Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
            Str_Sql = " insert into selinlib.JFCONCIBAN  (ctamov,descrip, debmov, cremov , fecmov , docmov, nummov,termov) " +
                             " select ctamov,descrip, debmov, cremov , fecmov , docmov  " +
                             " , nummov,termov " +
                             " from selinlib.jbancos , condat2006.movimi  " +
                             " where trim(char(ctamov)) = trim(char(cuenta)) and fecmov >="+this.jTFechaIncial.trim()+" and fecmov<= "+jTFechaFinal.trim();
            
            Rs = JBase_Datos.Exc_Sql(this.Cn,Str_Sql); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," setBancos()"+e.getMessage() );
        }
    }
    
    public void getComplemento_Cuenta(String docmov, String nummov, String Cta, String Fecha){
        try {
            String Str_Sql= " select ctamov , debmov , cremov , termov " +
                            " from condat2006.movimi " +
                            " where fecmov="+Fecha+" and " +
                            " docmov='"+docmov.trim()+"' and nummov ='"+nummov.trim()+"' " +
                            " and trim(char(ctamov))<>'"+Cta.trim()+"' ";
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            this.Ctamov2="";
            this.Debmov2="";
            this.Credmov2="";
            this.Termov2="";
            
            if(Rs.next()){
                this.Ctamov2=Rs.getString("ctamov");
                this.Debmov2=Rs.getString("debmov");
                this.Credmov2=Rs.getString("cremov");
                this.Termov2=Rs.getString("termov");
                
                Str_Sql =" update  selinlib.JFCONCIBAN"
                        + ""
                        + "where trim(char(cuenta))="+Cta.trim()+" and fecmov="+Fecha;
//                boolean Rs2 = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
            }
            //Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," getComplemento_Cuenta(String docmov, String nummov, String Cta)"+e.getMessage() );
        }
    }
            
     public void setTabla(){
        try {
            String Str_Sql = " select * from selinlib.JFCONCIBAN Where fecmov >="+jTFechaIncial.trim()+" and fecmov<= "+jTFechaFinal.trim();
            ResultSet Rs = JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            String Ctamov, Docmov, Nummov;
            while(Rs.next()){
                this.Detalle = new Vector();
                Ctamov = Rs.getString("ctamov");
                this.Detalle.add(Ctamov);
                this.Detalle.add(Rs.getString("descrip"));
                this.Detalle.add(this.JFormato.format(Rs.getDouble("debmov")));
                this.Detalle.add(this.JFormato.format(Rs.getDouble("cremov")));
                String PFecha = Rs.getString("fecmov");
                this.Detalle.add(PFecha);
                Docmov = Rs.getString("docmov");
                this.Detalle.add(Docmov);
                Nummov= Rs.getString("nummov");
                this.Detalle.add(Nummov);
                getComplemento_Cuenta(Docmov, Nummov, Ctamov,PFecha);
                this.Detalle.add(Ctamov2);
                this.Detalle.add(Credmov2);
                this.Detalle.add(Debmov2);
                this.Fila.add(Detalle);
            }
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," setTabla()"+e.getMessage() );
        }
        this.jTable1.setModel(new javax.swing.table.DefaultTableModel(this.Fila, this.Cabecera));
    }
    
    public void setCabecera(){
        this.Cabecera.clear();
        this.Cabecera.add("Cuenta");
        this.Cabecera.add("Descripcion");
        this.Cabecera.add("Debito");
        this.Cabecera.add("Credito");
        this.Cabecera.add("Fecha");
        this.Cabecera.add("Documento Fuente");
        this.Cabecera.add("Numero de Documento");
        this.Cabecera.add("Cuenta2");
        this.Cabecera.add("Debito");
        this.Cabecera.add("Credito");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JConcialiaBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JConcialiaBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JConcialiaBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JConcialiaBancos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JConcialiaBancos(null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker4;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker6;
    // End of variables declaration//GEN-END:variables
}
